[package]
name = "WarpToadCore"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v1.2.1", directory="noir-projects/aztec-nr/aztec" }
value_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v1.2.1", directory="noir-projects/aztec-nr/value-note"}
easy_private_state = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v1.2.1", directory="noir-projects/aztec-nr/easy-private-state"}
protocol_types = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v1.2.1", directory="noir-projects/noir-protocol-circuits/crates/types" }
trees = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "main", directory = "packages/merkle-trees" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v1.2.1", directory="noir-projects/noir-contracts/contracts/app/token_contract" }
compressed_string = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v1.2.1", directory="noir-projects/aztec-nr/compressed-string" }
hashing = { path = "../../../circuits/hashing" }
constants = { path = "../../../circuits/constants" }