/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRollup } from "./IRollup";
export type { IRollupCore } from "./IRollupCore";
export type { ITestRollup } from "./ITestRollup";
