/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IStakingCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deposit"
      | "finaliseWithdraw"
      | "initiateWithdraw"
      | "slash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposit"
      | "Slashed"
      | "WithdrawFinalised"
      | "WithdrawInitiated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finaliseWithdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateWithdraw",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "slash",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finaliseWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "slash", data: BytesLike): Result;
}

export namespace DepositEvent {
  export type InputTuple = [
    attester: AddressLike,
    proposer: AddressLike,
    withdrawer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    attester: string,
    proposer: string,
    withdrawer: string,
    amount: bigint
  ];
  export interface OutputObject {
    attester: string;
    proposer: string;
    withdrawer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlashedEvent {
  export type InputTuple = [attester: AddressLike, amount: BigNumberish];
  export type OutputTuple = [attester: string, amount: bigint];
  export interface OutputObject {
    attester: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawFinalisedEvent {
  export type InputTuple = [
    attester: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    attester: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    attester: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawInitiatedEvent {
  export type InputTuple = [
    attester: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    attester: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    attester: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IStakingCore extends BaseContract {
  connect(runner?: ContractRunner | null): IStakingCore;
  waitForDeployment(): Promise<this>;

  interface: IStakingCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deposit: TypedContractMethod<
    [
      _attester: AddressLike,
      _proposer: AddressLike,
      _withdrawer: AddressLike,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  finaliseWithdraw: TypedContractMethod<
    [_attester: AddressLike],
    [void],
    "nonpayable"
  >;

  initiateWithdraw: TypedContractMethod<
    [_attester: AddressLike, _recipient: AddressLike],
    [boolean],
    "nonpayable"
  >;

  slash: TypedContractMethod<
    [_attester: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      _attester: AddressLike,
      _proposer: AddressLike,
      _withdrawer: AddressLike,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finaliseWithdraw"
  ): TypedContractMethod<[_attester: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initiateWithdraw"
  ): TypedContractMethod<
    [_attester: AddressLike, _recipient: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slash"
  ): TypedContractMethod<
    [_attester: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "Slashed"
  ): TypedContractEvent<
    SlashedEvent.InputTuple,
    SlashedEvent.OutputTuple,
    SlashedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawFinalised"
  ): TypedContractEvent<
    WithdrawFinalisedEvent.InputTuple,
    WithdrawFinalisedEvent.OutputTuple,
    WithdrawFinalisedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawInitiated"
  ): TypedContractEvent<
    WithdrawInitiatedEvent.InputTuple,
    WithdrawInitiatedEvent.OutputTuple,
    WithdrawInitiatedEvent.OutputObject
  >;

  filters: {
    "Deposit(address,address,address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "Slashed(address,uint256)": TypedContractEvent<
      SlashedEvent.InputTuple,
      SlashedEvent.OutputTuple,
      SlashedEvent.OutputObject
    >;
    Slashed: TypedContractEvent<
      SlashedEvent.InputTuple,
      SlashedEvent.OutputTuple,
      SlashedEvent.OutputObject
    >;

    "WithdrawFinalised(address,address,uint256)": TypedContractEvent<
      WithdrawFinalisedEvent.InputTuple,
      WithdrawFinalisedEvent.OutputTuple,
      WithdrawFinalisedEvent.OutputObject
    >;
    WithdrawFinalised: TypedContractEvent<
      WithdrawFinalisedEvent.InputTuple,
      WithdrawFinalisedEvent.OutputTuple,
      WithdrawFinalisedEvent.OutputObject
    >;

    "WithdrawInitiated(address,address,uint256)": TypedContractEvent<
      WithdrawInitiatedEvent.InputTuple,
      WithdrawInitiatedEvent.OutputTuple,
      WithdrawInitiatedEvent.OutputObject
    >;
    WithdrawInitiated: TypedContractEvent<
      WithdrawInitiatedEvent.InputTuple,
      WithdrawInitiatedEvent.OutputTuple,
      WithdrawInitiatedEvent.OutputObject
    >;
  };
}
