
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
    type AbiType,
    AztecAddress,
    type AztecAddressLike,
    CompleteAddress,
    Contract,
    type ContractArtifact,
    ContractBase,
    ContractFunctionInteraction,
    type ContractInstanceWithAddress,
    type ContractMethod,
    type ContractStorageLayout,
    type ContractNotes,
    decodeFromAbi,
    DeployMethod,
    EthAddress,
    type EthAddressLike,
    EventSelector,
    type FieldLike,
    Fr,
    type FunctionSelectorLike,
    loadContractArtifact,
    loadContractArtifactForPublic,
    type NoirCompiledContract,
    NoteSelector,
    Point,
    type PublicKey,
    PublicKeys,
    type Wallet,
    type U128Like,
    type WrappedFieldLike,
    //@ts-ignore
  } from '@aztec/aztec.js';
  // @ts-ignore
  import ObsidionDeployerFPCContractArtifactJson from './obsidion_deployer_fpc-ObsidionDeployerFPC.json' assert { type: 'json' };
  export const ObsidionDeployerFPCContractArtifact = loadContractArtifact(ObsidionDeployerFPCContractArtifactJson as NoirCompiledContract);
  
  
  
  /**
   * Type-safe interface for contract ObsidionDeployerFPC;
   */
  export class ObsidionDeployerFPCContract extends ContractBase {
    
    private constructor(
      instance: ContractInstanceWithAddress,
      wallet: Wallet,
    ) {
      super(instance, ObsidionDeployerFPCContractArtifact, wallet);
    }
    
  
    
    /**
     * Creates a contract instance.
     * @param address - The deployed contract's address.
     * @param wallet - The wallet to use when interacting with the contract.
     * @returns A promise that resolves to a new Contract instance.
     */
    public static async at(
      address: AztecAddress,
      wallet: Wallet,
    ) {
      return Contract.at(address, ObsidionDeployerFPCContract.artifact, wallet) as Promise<ObsidionDeployerFPCContract>;
    }
  
    
    /**
     * Creates a tx to deploy a new instance of this contract.
     */
    public static deploy(wallet: Wallet, signing_pub_key_x: FieldLike, signing_pub_key_y: FieldLike) {
      return new DeployMethod<ObsidionDeployerFPCContract>(PublicKeys.default(), wallet, ObsidionDeployerFPCContractArtifact, ObsidionDeployerFPCContract.at, Array.from(arguments).slice(1));
    }
  
    /**
     * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
     */
    public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, signing_pub_key_x: FieldLike, signing_pub_key_y: FieldLike) {
      return new DeployMethod<ObsidionDeployerFPCContract>(publicKeys, wallet, ObsidionDeployerFPCContractArtifact, ObsidionDeployerFPCContract.at, Array.from(arguments).slice(2));
    }
  
    /**
     * Creates a tx to deploy a new instance of this contract using the specified constructor method.
     */
    public static deployWithOpts<M extends keyof ObsidionDeployerFPCContract['methods']>(
      opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
      ...args: Parameters<ObsidionDeployerFPCContract['methods'][M]>
    ) {
      return new DeployMethod<ObsidionDeployerFPCContract>(
        opts.publicKeys ?? PublicKeys.default(),
        opts.wallet,
        ObsidionDeployerFPCContractArtifact,
        ObsidionDeployerFPCContract.at,
        Array.from(arguments).slice(1),
        opts.method ?? 'constructor',
      );
    }
    
  
    
    /**
     * Returns this contract's artifact.
     */
    public static get artifact(): ContractArtifact {
      return ObsidionDeployerFPCContractArtifact;
    }
  
    /**
     * Returns this contract's artifact with public bytecode.
     */
    public static get artifactForPublic(): ContractArtifact {
      return loadContractArtifactForPublic(ObsidionDeployerFPCContractArtifactJson as NoirCompiledContract);
    }
    
  
    public static get storage(): ContractStorageLayout<'signing_public_key'> {
        return {
          signing_public_key: {
        slot: new Fr(1n),
      }
        } as ContractStorageLayout<'signing_public_key'>;
      }
      
  
    public static get notes(): ContractNotes<'PublicKeyNote'> {
      return {
        PublicKeyNote: {
            id: new NoteSelector(0),
          }
      } as ContractNotes<'PublicKeyNote'>;
    }
    
  
    /** Type-safe wrappers for the public methods exposed by the contract. */
    public declare methods: {
      
      /** constructor(signing_pub_key_x: field, signing_pub_key_y: field) */
      constructor: ((signing_pub_key_x: FieldLike, signing_pub_key_y: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  
      /** entrypoint(app_payload: struct, fee_payload: struct, cancellable: boolean) */
      entrypoint: ((app_payload: { function_calls: { args_hash: FieldLike, function_selector: FunctionSelectorLike, target_address: AztecAddressLike, is_public: boolean, is_static: boolean }[], nonce: FieldLike }, fee_payload: { function_calls: { args_hash: FieldLike, function_selector: FunctionSelectorLike, target_address: AztecAddressLike, is_public: boolean, is_static: boolean }[], nonce: FieldLike, is_fee_payer: boolean }, cancellable: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  
      /** fee_entrypoint_private(max_fee: integer, nonce: field) */
      fee_entrypoint_private: ((max_fee: (bigint | number), nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  
      /** fee_entrypoint_public(max_fee: integer, nonce: field) */
      fee_entrypoint_public: ((max_fee: (bigint | number), nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  
      /** get_accepted_asset() */
      get_accepted_asset: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  
      /** lookup_validity(consumer: struct, inner_hash: field) */
      lookup_validity: ((consumer: AztecAddressLike, inner_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  
      /** public_dispatch(selector: field) */
      public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  
      /** sync_notes() */
      sync_notes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  
      /** verify_private_authwit(inner_hash: field) */
      verify_private_authwit: ((inner_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
    };
  
    
  }