/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IGigaRootProviderInterface extends Interface {
  getFunction(nameOrSignature: "gigaRoot" | "sendGigaRoot"): FunctionFragment;

  encodeFunctionData(functionFragment: "gigaRoot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sendGigaRoot",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "gigaRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendGigaRoot",
    data: BytesLike
  ): Result;
}

export interface IGigaRootProvider extends BaseContract {
  connect(runner?: ContractRunner | null): IGigaRootProvider;
  waitForDeployment(): Promise<this>;

  interface: IGigaRootProviderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  gigaRoot: TypedContractMethod<[], [bigint], "nonpayable">;

  sendGigaRoot: TypedContractMethod<
    [_gigaRootRecipient: AddressLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "gigaRoot"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "sendGigaRoot"
  ): TypedContractMethod<[_gigaRootRecipient: AddressLike], [void], "payable">;

  filters: {};
}
