/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGigaRootProvider } from "./IGigaRootProvider";
export type { IGigaRootRecipient } from "./IGigaRootRecipient";
export type { ILocalRootProvider } from "./ILocalRootProvider";
