/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITestRollup,
  ITestRollupInterface,
} from "../../../../../contracts/evm/aztec-interfaces/IRollup.sol/ITestRollup";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "manaTarget",
        type: "uint256",
      },
    ],
    name: "ManaTargetUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "attester",
            type: "address",
          },
          {
            internalType: "address",
            name: "proposer",
            type: "address",
          },
          {
            internalType: "address",
            name: "withdrawer",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
        ],
        internalType: "struct CheatDepositArgs[]",
        name: "_args",
        type: "tuple[]",
      },
    ],
    name: "cheat__InitialiseValidatorSet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_verifier",
        type: "address",
      },
    ],
    name: "setEpochVerifier",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_protocolContractTreeRoot",
        type: "bytes32",
      },
    ],
    name: "setProtocolContractTreeRoot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_vkTreeRoot",
        type: "bytes32",
      },
    ],
    name: "setVkTreeRoot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_manaTarget",
        type: "uint256",
      },
    ],
    name: "updateManaTarget",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITestRollup__factory {
  static readonly abi = _abi;
  static createInterface(): ITestRollupInterface {
    return new Interface(_abi) as ITestRollupInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ITestRollup {
    return new Contract(address, _abi, runner) as unknown as ITestRollup;
  }
}
