/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICoinIssuer,
  ICoinIssuerInterface,
} from "../../../../contracts/evm/aztec-interfaces/ICoinIssuer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "mintAvailable",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICoinIssuer__factory {
  static readonly abi = _abi;
  static createInterface(): ICoinIssuerInterface {
    return new Interface(_abi) as ICoinIssuerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICoinIssuer {
    return new Contract(address, _abi, runner) as unknown as ICoinIssuer;
  }
}
