/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISlasher,
  ISlasherInterface,
} from "../../../../contracts/evm/aztec-interfaces/ISlasher";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IPayload",
        name: "_payload",
        type: "address",
      },
    ],
    name: "slash",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISlasher__factory {
  static readonly abi = _abi;
  static createInterface(): ISlasherInterface {
    return new Interface(_abi) as ISlasherInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISlasher {
    return new Contract(address, _abi, runner) as unknown as ISlasher;
  }
}
