/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as coreErrorsSol from "./CoreErrors.sol";
export type { coreErrorsSol };
import type * as governanceErrorsSol from "./GovernanceErrors.sol";
export type { governanceErrorsSol };
import type * as iRollupSol from "./IRollup.sol";
export type { iRollupSol };
import type * as iStakingSol from "./IStaking.sol";
export type { iStakingSol };
import type * as iValidatorSelectionSol from "./IValidatorSelection.sol";
export type { iValidatorSelectionSol };
import type * as vmSol from "./Vm.sol";
export type { vmSol };
import type * as messagebridge from "./messagebridge";
export type { messagebridge };
import type * as rollup from "./rollup";
export type { rollup };
export type { ICoinIssuer } from "./ICoinIssuer";
export type { IFeeJuicePortal } from "./IFeeJuicePortal";
export type { IGovernance } from "./IGovernance";
export type { IGovernanceProposer } from "./IGovernanceProposer";
export type { IInstance } from "./IInstance";
export type { IMintableERC20 } from "./IMintableERC20";
export type { IPayload } from "./IPayload";
export type { IRegistry } from "./IRegistry";
export type { IRewardDistributor } from "./IRewardDistributor";
export type { ISlasher } from "./ISlasher";
export type { IVerifier } from "./IVerifier";
