/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IInbox,
  IInboxInterface,
} from "../../../../../contracts/evm/aztec-interfaces/messagebridge/IInbox";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "l2BlockNumber",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
    ],
    name: "MessageSent",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_toConsume",
        type: "uint256",
      },
    ],
    name: "consume",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_blockNumber",
        type: "uint256",
      },
    ],
    name: "getRoot",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "actor",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "version",
            type: "uint256",
          },
        ],
        internalType: "struct DataStructures.L2Actor",
        name: "_recipient",
        type: "tuple",
      },
      {
        internalType: "bytes32",
        name: "_content",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "_secretHash",
        type: "bytes32",
      },
    ],
    name: "sendL2Message",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IInbox__factory {
  static readonly abi = _abi;
  static createInterface(): IInboxInterface {
    return new Interface(_abi) as IInboxInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IInbox {
    return new Contract(address, _abi, runner) as unknown as IInbox;
  }
}
