[package]
name = "nargo_hashing"
type = "lib"
authors = [""]

[dependencies]
trees = { path = "../merkle-trees" }
constants = { path = "../constants" }
poseidon = { tag = "v0.3.0", git = "https://github.com/noir-lang/poseidon" }