/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IValidatorSelection } from "./IValidatorSelection";
export type { IValidatorSelectionCore } from "./IValidatorSelectionCore";
