/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGigaRootProvider,
  IGigaRootProviderInterface,
} from "../../../../../contracts/evm/interfaces/IRootMessengers.sol/IGigaRootProvider";

const _abi = [
  {
    inputs: [],
    name: "gigaRoot",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_gigaRootRecipient",
        type: "address",
      },
    ],
    name: "sendGigaRoot",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IGigaRootProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IGigaRootProviderInterface {
    return new Interface(_abi) as IGigaRootProviderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGigaRootProvider {
    return new Contract(address, _abi, runner) as unknown as IGigaRootProvider;
  }
}
