/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGigaRootRecipient,
  IGigaRootRecipientInterface,
} from "../../../../../contracts/evm/interfaces/IRootMessengers.sol/IGigaRootRecipient";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_gigaRoot",
        type: "uint256",
      },
    ],
    name: "receiveGigaRoot",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IGigaRootRecipient__factory {
  static readonly abi = _abi;
  static createInterface(): IGigaRootRecipientInterface {
    return new Interface(_abi) as IGigaRootRecipientInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGigaRootRecipient {
    return new Contract(address, _abi, runner) as unknown as IGigaRootRecipient;
  }
}
