/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILocalRootProvider,
  ILocalRootProviderInterface,
} from "../../../../../contracts/evm/interfaces/IRootMessengers.sol/ILocalRootProvider";

const _abi = [
  {
    inputs: [],
    name: "getLocalRootAndBlock",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILocalRootProvider__factory {
  static readonly abi = _abi;
  static createInterface(): ILocalRootProviderInterface {
    return new Interface(_abi) as ILocalRootProviderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILocalRootProvider {
    return new Contract(address, _abi, runner) as unknown as ILocalRootProvider;
  }
}
