/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGigaRootProvider__factory } from "./IGigaRootProvider__factory";
export { IGigaRootRecipient__factory } from "./IGigaRootRecipient__factory";
export { ILocalRootProvider__factory } from "./ILocalRootProvider__factory";
