/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc206DecSol from "./ERC206Dec.sol";
export type { erc206DecSol };
export type { USDcoin } from "./USDcoin";
