/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as warpToadCoreSol from "./WarpToadCore.sol";
export type { warpToadCoreSol };
export type { L1WarpToad } from "./L1WarpToad";
export type { L2WarpToad } from "./L2WarpToad";
