/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IValidatorSelectionCore,
  IValidatorSelectionCoreInterface,
} from "../../../../../contracts/evm/aztec-interfaces/IValidatorSelection.sol/IValidatorSelectionCore";

const _abi = [
  {
    inputs: [],
    name: "setupEpoch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IValidatorSelectionCore__factory {
  static readonly abi = _abi;
  static createInterface(): IValidatorSelectionCoreInterface {
    return new Interface(_abi) as IValidatorSelectionCoreInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IValidatorSelectionCore {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IValidatorSelectionCore;
  }
}
