/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IValidatorSelection,
  IValidatorSelectionInterface,
} from "../../../../../contracts/evm/aztec-interfaces/IValidatorSelection.sol/IValidatorSelection";

const _abi = [
  {
    inputs: [],
    name: "getAttesters",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "Timestamp",
        name: "_ts",
        type: "uint256",
      },
    ],
    name: "getCommitteeAt",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentEpoch",
    outputs: [
      {
        internalType: "Epoch",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentEpochCommittee",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentProposer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentSampleSeed",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentSlot",
    outputs: [
      {
        internalType: "Slot",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "Timestamp",
        name: "_ts",
        type: "uint256",
      },
    ],
    name: "getEpochAt",
    outputs: [
      {
        internalType: "Epoch",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "Slot",
        name: "_slotNumber",
        type: "uint256",
      },
    ],
    name: "getEpochAtSlot",
    outputs: [
      {
        internalType: "Epoch",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "Epoch",
        name: "_epoch",
        type: "uint256",
      },
    ],
    name: "getEpochCommittee",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getEpochDuration",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getGenesisTime",
    outputs: [
      {
        internalType: "Timestamp",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "Timestamp",
        name: "_ts",
        type: "uint256",
      },
    ],
    name: "getProposerAt",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "Timestamp",
        name: "_ts",
        type: "uint256",
      },
    ],
    name: "getSampleSeedAt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "Timestamp",
        name: "_ts",
        type: "uint256",
      },
    ],
    name: "getSlotAt",
    outputs: [
      {
        internalType: "Slot",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSlotDuration",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTargetCommitteeSize",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "Slot",
        name: "_slotNumber",
        type: "uint256",
      },
    ],
    name: "getTimestampForSlot",
    outputs: [
      {
        internalType: "Timestamp",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "setupEpoch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IValidatorSelection__factory {
  static readonly abi = _abi;
  static createInterface(): IValidatorSelectionInterface {
    return new Interface(_abi) as IValidatorSelectionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IValidatorSelection {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IValidatorSelection;
  }
}
