/**
 * Aztec interactions for cross-chain bridging
 * 
 * This module handles bidirectional bridging between L1 (EVM) and Aztec L2.
 * 
 * L1 -> Aztec flow:
 * 1. User burns tokens on L1 with a commitment
 * 2. Relayer bridges the local root to GigaBridge, which creates a gigaRoot
 * 3. GigaRoot is sent to Aztec WarpToad contract
 * 4. User can withdraw on Aztec by proving their commitment is in the tree
 * 
 * Aztec -> L1 flow:
 * 1. User burns tokens on Aztec with a commitment (stored as WarpToadNote)
 * 2. Relayer bridges the Aztec note hash tree root to L1 GigaBridge
 * 3. GigaRoot is updated on L1
 * 4. User generates ZK proof and claims on L1 (with optional auto-unwrap)
 */

import type { CommitmentPreImage } from '$lib/types/bridge';
import { createPublicClient, http, keccak256, toHex, type PublicClient } from 'viem';
import { getContractAddresses, CONTRACT_ADDRESSES } from '$lib/contracts/addresses';
import { GigaBridgeAbi, L1WarpToadAbi, L2WarpToadAbi } from '$lib/contracts/abis';
import { queryEventInChunks } from './viem-chunks';
import { rpcSettings } from '$lib/stores/rpc-settings.svelte';
import { fetchGigaStateFromKeeper } from './bridge-keeper';
import { poseidon1, poseidon2, poseidon3 } from 'poseidon-lite';
import { MerkleTree, type Element } from 'fixed-merkle-tree';
import { AztecAddress } from '@aztec/aztec.js/addresses';
import type { Wallet } from '@aztec/aztec.js/wallet';
import type { AztecNode } from '@aztec/aztec.js/node';
import { createAztecNodeClient } from '@aztec/aztec.js/node';
// Aztec contract codegen lives in the backend tree (regenerated by `aztec codegen`).
// We import it via the @backend Vite alias rather than copying the artifact.
// This is BUILD-time path resolution only - the bundled output is fully self-contained
// and doesn't pull in any other backend code.
import { WarpToadCoreContract, WarpToadCoreContractArtifact } from '@backend/aztec/WarpToadCore/src/artifacts/WarpToadCore';
import { loadContractArtifact } from '@aztec/aztec.js/abi';
import { getContractInstanceFromInstantiationParams, type ContractInstanceWithAddress } from '@aztec/aztec.js/contracts';
import { AZTEC_CONTRACTS, AZTEC_CONFIG, L1_CONFIG } from '$lib/config/environment.js';
import { getSponsoredPaymentMethod } from '$lib/utils/aztec-wallet.js';
import { Fr } from '@aztec/aztec.js/fields';
import { MerkleTreeId } from '@aztec/stdlib/trees';
import { siloNullifier } from '@aztec/stdlib/hash';


// =============================================================================
// CONSTANTS
// =============================================================================

const EVM_TREE_DEPTH = 32;
const GIGA_TREE_DEPTH = 5;

// Environment configuration
const getAztecNodeUrl = () => AZTEC_CONFIG.nodeUrl;

/**
 * Get deployment block for a chain (fallback to recent blocks if not available)
 * This prevents scanning from block 0 which would timeout on testnets
 */
function getDeploymentBlock(chainId: number): bigint {
	const chainData = CONTRACT_ADDRESSES[chainId.toString()];
	if (chainData?.deploymentBlock) {
		return BigInt(chainData.deploymentBlock);
	}
	// Fallback: use 0 for localhost, recent blocks for others
	return chainId === 31337 ? 0n : 0n; // Will be replaced with current block - 10000 in actual calls
}

// =============================================================================
// TYPES
// =============================================================================

export interface EvmMerkleData {
	leaf_index: bigint;
	hash_path: bigint[];
}

export interface MerkleDataResult {
	blockNumber: number;
	originLocalRoot: bigint;
	gigaMerkleData: EvmMerkleData;
	evmMerkleData: EvmMerkleData;
	actualGigaRoot?: bigint; // The gigaRoot actually used for proofs (may differ from Aztec's current gigaRoot for Scroll)
}

interface LocalRootData {
	localRoot: bigint;
	localRootIndex: number;
	localRootBlockNumber: number;
	gigaRootBlockNumber: number;
}

/**
 * Aztec merkle data for proving commitment inclusion in note hash tree
 * Used for Aztec -> L1 withdrawals
 */
export interface AztecMerkleData {
	leaf_index: bigint;
	hash_path: bigint[];
	leaf_nonce: bigint;
	contract_address: bigint;
}

/**
 * Result of burning tokens on Aztec
 */
export interface AztecBurnResult {
	secret: bigint;
	nullifierPreimage: bigint;
	preCommitment: bigint;
	commitment: bigint;
	burnTxHash: string;
	blockNumber: number;
}

// Aztec tree depth for note hash tree
const AZTEC_TREE_DEPTH = 42;

// Generator indexes for Aztec note hashing. These are domain separators used by
// poseidon2HashWithSeparator and MUST match the values in backend/lib/constants.ts.
// Using the wrong values silently produces hashes that don't match the note hash tree.
const GENERATOR_INDEX__NOTE_HASH_NONCE = 1721808740n;
const GENERATOR_INDEX__UNIQUE_NOTE_HASH = 226850429n;
const GENERATOR_INDEX__SILOED_NOTE_HASH = 3361878420n;

// =============================================================================
// AZTEC NODE CLIENT
// =============================================================================

let aztecNodeInstance: AztecNode | null = null;

/**
 * Get or create Aztec node client
 */
export async function getAztecNode(): Promise<AztecNode> {
	if (aztecNodeInstance) {
		return aztecNodeInstance;
	}

	const nodeUrl = getAztecNodeUrl();
	console.log('Creating Aztec Node Client at:', nodeUrl);

	aztecNodeInstance = createAztecNodeClient(nodeUrl);

	try {
		const nodeInfo = await aztecNodeInstance.getNodeInfo();
		console.log('Connected to Aztec sandbox version:', nodeInfo.nodeVersion);
		console.log('L1 Chain ID:', nodeInfo.l1ChainId);
	} catch (error) {
		console.error('Failed to connect to Aztec node:', error);
		aztecNodeInstance = null;
		throw new Error(
			`Cannot connect to Aztec node at ${nodeUrl}. ` +
			'Make sure the sandbox is running: aztec start --sandbox'
		);
	}

	return aztecNodeInstance;
}

// =============================================================================
// WARPTOAD CONTRACT
// =============================================================================

/**
 * Get WarpToadCore contract instance connected to wallet
 */
export async function getWarpToadContract(wallet: Wallet): Promise<WarpToadCoreContract> {
	const contract = await getContractInstanceFromInstantiationParams(
		WarpToadCoreContractArtifact,
		{
			constructorArgs: AZTEC_CONTRACTS.AztecWarpToad.constructorArgs,
			deployer: AztecAddress.fromString(AZTEC_CONTRACTS.AztecWarpToad.deployer),
			salt: Fr.fromHexString(AZTEC_CONTRACTS.AztecWarpToad.contractAddressSalt),
		}
	);

	const registeredContract = await wallet.registerContract(
		contract,
		WarpToadCoreContractArtifact
	);

	const warptoadContract = await WarpToadCoreContract.at(registeredContract.address, wallet);

	return warptoadContract;
}

// =============================================================================
// HASHING UTILITIES
// =============================================================================

/**
 * Hash pre-commitment: poseidon3(nullifier_preimage, secret, chain_id)
 */
export function hashPreCommitment(
	nullifierPreimage: bigint,
	secret: bigint,
	chainId: bigint
): bigint {
	return poseidon3([nullifierPreimage, secret, chainId]);
}

/**
 * Hash commitment: poseidon2(pre_commitment, amount)
 */
export function hashCommitment(preCommitment: bigint, amount: bigint): bigint {
	return poseidon2([preCommitment, amount]);
}

/**
 * Hash nullifier: poseidon1(nullifier_preimage)
 * This matches the Noir circuit: poseidon::bn254::hash_1([nullifier_preimage])
 */
export function hashNullifier(nullifierPreimage: bigint): bigint {
	return poseidon1([nullifierPreimage]);
}

// =============================================================================
// EVM CLIENT HELPERS
// =============================================================================

/**
 * Create a public client for the given chain
 */
function createEvmClient(chainId: number, rpcUrl?: string): PublicClient {
	// Use environment config for RPC URLs
	let defaultRpcUrl: string | undefined;
	if (chainId === L1_CONFIG.chainId || chainId === 31337) {
		defaultRpcUrl = L1_CONFIG.rpcUrl;
	} else if (chainId === 11155111) {
		defaultRpcUrl = import.meta.env.VITE_SEPOLIA_RPC_URL;
	} else if (chainId === 534351) {
		defaultRpcUrl = import.meta.env.VITE_SCROLL_SEPOLIA_RPC_URL;
	}

	const resolvedRpc = rpcUrl ?? defaultRpcUrl;
	if (!resolvedRpc) {
		throw new Error(
			`[createEvmClient] No RPC URL configured for chainId ${chainId}. ` +
			`Pass an explicit rpcUrl or set the corresponding VITE_*_RPC_URL build arg.`
		);
	}

	return createPublicClient({
		chain: {
			id: chainId,
			name: chainId === 31337 ? 'Localhost' : chainId === 11155111 ? 'Sepolia' : `Chain ${chainId}`,
			nativeCurrency: { name: 'ETH', symbol: 'ETH', decimals: 18 },
			rpcUrls: {
				default: { http: [resolvedRpc] },
				public: { http: [resolvedRpc] },
			},
		},
		transport: http()
	});
}

// =============================================================================
// MERKLE TREE HELPERS
// =============================================================================

/**
 * Poseidon2 hash function wrapper for fixed-merkle-tree
 * The library expects (left, right) => hash
 */
const poseidonHashFunction = (left: Element, right: Element): string => {
	const result = poseidon2([BigInt(left.toString()), BigInt(right.toString())]);
	return result.toString();
};

/**
 * Create a Poseidon merkle tree using fixed-merkle-tree library
 * This handles sparse trees efficiently without allocating 2^depth elements
 */
function createPoseidonMerkleTree(depth: number, leaves: bigint[]): MerkleTree {
	// Convert bigints to strings for the library
	const leavesAsStrings = leaves.map(l => l.toString());
	return new MerkleTree(depth, leavesAsStrings, { hashFunction: poseidonHashFunction });
}

/**
 * Get merkle proof from a tree
 * Returns the path elements and leaf index in the format expected by the contract
 */
function getMerkleProof(tree: MerkleTree, leafValue: bigint): { pathElements: bigint[]; leafIndex: number } {
	const proof = tree.proof(leafValue.toString() as Element);

	return {
		pathElements: proof.pathElements.map(e => BigInt(e.toString())),
		leafIndex: proof.pathIndices.reduce((acc, bit, i) => acc + (bit ? Math.pow(2, i) : 0), 0),
	};
}

// =============================================================================
// EVENT QUERYING
// =============================================================================

/**
 * Query Burn events from L1WarpToad to get all commitments
 */
async function getBurnEvents(
	publicClient: PublicClient,
	warpToadAddress: string,
	chainId: number,
	toBlock: bigint | 'latest' = 'latest'
): Promise<Array<{ commitment: bigint; amount: bigint; index: number }>> {
	const fromBlock = getDeploymentBlock(chainId);
	const lastBlock = toBlock === 'latest' ? undefined : toBlock;

	const logs = await queryEventInChunks({
		publicClient,
		contract: { address: warpToadAddress as `0x${string}`, abi: L1WarpToadAbi },
		eventName: 'Burn',
		firstBlock: fromBlock,
		lastBlock,
	});

	return logs.map((log: any) => ({
		commitment: log.args.commitment as bigint,
		amount: log.args.amount as bigint,
		index: Number(log.args.index),
	}));
}

/**
 * Query ReceivedNewLocalRoot events from GigaBridge
 * 
 * Event signature: ReceivedNewLocalRoot(uint256 indexed newLocalRoot, uint40 indexed localRootIndex, uint256 localRootBlockNumber)
 */
async function getLocalRootEvents(
	publicClient: PublicClient,
	gigaBridgeAddress: string,
	chainId: number,
	toBlock: bigint | 'latest' = 'latest'
): Promise<Array<{ localRoot: bigint; index: number; blockNumber: number; eventBlockNumber: bigint }>> {
	const fromBlock = getDeploymentBlock(chainId);
	const lastBlock = toBlock === 'latest' ? undefined : toBlock;

	// Reverse-scan with a small cap so we don't rescan ~700k blocks every time.
	// We only need the LATEST event per local-root index to reconstruct the
	// giga tree leaves; in practice recent updateGigaRoot calls emit all
	// three leaves close together near `toBlock`, so a handful of chunks
	// already fills the window. The cap is generous enough to tolerate
	// skewed emission (e.g. aztec leaf updated long before scroll leaf).
	const logs = await queryEventInChunks({
		publicClient,
		contract: { address: gigaBridgeAddress as `0x${string}`, abi: GigaBridgeAbi },
		eventName: 'ReceivedNewLocalRoot',
		firstBlock: fromBlock,
		lastBlock,
		reverseOrder: true,
		maxEvents: 30,
	});

	return logs.map((log: any) => ({
		localRoot: log.args.newLocalRoot as bigint,
		index: Number(log.args.localRootIndex),
		blockNumber: Number(log.args.localRootBlockNumber),
		eventBlockNumber: log.blockNumber,
	}));
}

/**
 * Find the most recent ReceivedNewLocalRoot event for one provider index at or
 * before `upToBlock`. GigaBridge.updateGigaRoot only emits the event for the
 * providers passed into that call; other providers' local roots stay in the
 * tree from earlier updates. To reconstruct the leaves of a historical
 * gigaRoot we must walk the log backwards per index, not just look at events
 * emitted in the construction block.
 */
export async function getLatestLocalRootEventForIndex(
	publicClient: PublicClient,
	gigaBridgeAddress: string,
	chainId: number,
	index: number,
	upToBlock: bigint
): Promise<{ localRoot: bigint; index: number; blockNumber: number; eventBlockNumber: bigint } | null> {
	const fromBlock = getDeploymentBlock(chainId);
	const logs = await queryEventInChunks({
		publicClient,
		contract: { address: gigaBridgeAddress as `0x${string}`, abi: GigaBridgeAbi },
		eventName: 'ReceivedNewLocalRoot',
		eventFilterArgs: { localRootIndex: BigInt(index) } as any,
		firstBlock: fromBlock,
		lastBlock: upToBlock,
		reverseOrder: true,
		maxEvents: 1,
	});

	if (logs.length === 0) return null;
	const log = logs[logs.length - 1] as any;
	return {
		localRoot: log.args.newLocalRoot as bigint,
		index: Number(log.args.localRootIndex),
		blockNumber: Number(log.args.localRootBlockNumber),
		eventBlockNumber: log.blockNumber,
	};
}

/**
 * Query ConstructedNewGigaRoot events from GigaBridge
 * @param filterGigaRoot - If provided, only returns events for this specific gigaRoot value
 */
async function getGigaRootEvents(
	publicClient: PublicClient,
	gigaBridgeAddress: string,
	chainId: number,
	filterGigaRoot?: bigint
): Promise<Array<{ gigaRoot: bigint; blockNumber: bigint; transactionHash: `0x${string}` }>> {
	const fromBlock = getDeploymentBlock(chainId);

	// When filtering for a specific gigaRoot, scan backwards and stop at the first
	// hit - the event is emitted once and we don't need to scan deployment → head.
	const logs = await queryEventInChunks({
		publicClient,
		contract: { address: gigaBridgeAddress as `0x${string}`, abi: GigaBridgeAbi },
		eventName: 'ConstructedNewGigaRoot',
		eventFilterArgs: filterGigaRoot ? { newGigaRoot: filterGigaRoot } : undefined,
		firstBlock: fromBlock,
		reverseOrder: filterGigaRoot !== undefined,
		maxEvents: filterGigaRoot !== undefined ? 1 : Infinity,
	});

	return logs.map((log: any) => ({
		gigaRoot: log.args.newGigaRoot as bigint,
		blockNumber: log.blockNumber,
		transactionHash: log.transactionHash,
	}));
}

/**
 * Query GigaRoot events within a specific block range
 * Used for finding recent gigaRoots that might contain a commitment
 */
async function getGigaRootEventsInRange(
	publicClient: PublicClient,
	gigaBridgeAddress: string,
	fromBlock: bigint,
	toBlock: bigint
): Promise<Array<{ gigaRoot: bigint; blockNumber: number; transactionHash: `0x${string}` }>> {
	const logs = await queryEventInChunks({
		publicClient,
		contract: { address: gigaBridgeAddress as `0x${string}`, abi: GigaBridgeAbi },
		eventName: 'ConstructedNewGigaRoot',
		firstBlock: fromBlock,
		lastBlock: toBlock,
	});

	return logs.map((log: any) => ({
		gigaRoot: log.args.newGigaRoot as bigint,
		blockNumber: Number(log.blockNumber),
		transactionHash: log.transactionHash,
	}));
}

/**
 * Check if a commitment exists in burn events up to a specific block
 * Used to verify if a local root contains our commitment
 */
async function checkCommitmentInLocalRoot(
	publicClient: PublicClient,
	warpToadAddress: string,
	commitment: bigint,
	chainId: number,
	localRootBlockNumber: number
): Promise<boolean> {
	const burnEvents = await getBurnEvents(
		publicClient,
		warpToadAddress,
		chainId,
		BigInt(localRootBlockNumber)
	);

	// Check if our commitment is in these events
	return burnEvents.some(event => event.commitment === commitment);
}

/**
 * Find a gigaRoot that contains the given commitment from a specific source chain.
 * Searches recent gigaRoots on L1 (last ~6.5 hours) to find one that includes the commitment.
 * 
 * @param sourceChainId - Chain where the burn happened (e.g., 534351 for Scroll)
 * @param commitment - The commitment to search for
 * @param sourceWarpToadAddress - WarpToad contract address on source chain
 * @returns Object with gigaRoot, localRoot, localRootIndex, and localRootBlockNumber
 */
async function findGigaRootWithCommitment(
	sourceChainId: number,
	commitment: bigint,
	sourceWarpToadAddress: string
): Promise<{
	gigaRoot: bigint;
	localRoot: bigint;
	localRootIndex: number;
	localRootBlockNumber: number;
	gigaRootBlockNumber: number;
}> {
	const gigaBridgeChainId = getGigaBridgeChainId(sourceChainId);
	const gigaBridgeClient = createEvmClient(gigaBridgeChainId);
	const sourceClient = createEvmClient(sourceChainId);

	const gigaBridgeAddresses = getContractAddresses(gigaBridgeChainId);
	if (!gigaBridgeAddresses.GigaBridge) {
		throw new Error('GigaBridge address not found');
	}

	// Determine which local root provider to query
	let localRootProviderAddress: string;
	if (sourceChainId === 534351) {
		// For Scroll, use L1ScrollBridgeAdapter
		if (!gigaBridgeAddresses.L1ScrollBridgeAdapter) {
			throw new Error('L1ScrollBridgeAdapter address not found');
		}
		localRootProviderAddress = gigaBridgeAddresses.L1ScrollBridgeAdapter;
	} else {
		// For L1 chains, use L1WarpToad
		if (!gigaBridgeAddresses.L1WarpToad) {
			throw new Error('L1WarpToad address not found');
		}
		localRootProviderAddress = gigaBridgeAddresses.L1WarpToad;
	}

	console.log(`[findGigaRootWithCommitment] Searching for commitment ${commitment.toString()} from chain ${sourceChainId}`);
	console.log(`[findGigaRootWithCommitment] Using local root provider: ${localRootProviderAddress}`);

	// Get recent gigaRoots (last 2000 blocks ~ 6.5 hours on Sepolia)
	const currentBlock = await gigaBridgeClient.getBlockNumber();
	const searchFromBlock = currentBlock - 2000n;
	
	console.log(`[findGigaRootWithCommitment] Searching gigaRoots from block ${searchFromBlock} to ${currentBlock}`);

	const gigaRootEvents = await getGigaRootEventsInRange(
		gigaBridgeClient,
		gigaBridgeAddresses.GigaBridge,
		searchFromBlock,
		currentBlock
	);

	console.log(`[findGigaRootWithCommitment] Found ${gigaRootEvents.length} gigaRoot events`);

	if (gigaRootEvents.length === 0) {
		throw new Error(
			`No gigaRoot events found in the last 2000 blocks. The relayer may not have updated the gigaRoot recently. ` +
			`Please wait 1-3 hours after your burn transaction and try again.`
		);
	}

	// Search gigaRoots from newest to oldest
	for (const gigaRootEvent of gigaRootEvents.reverse()) {
		console.log(`[findGigaRootWithCommitment] Checking gigaRoot: ${gigaRootEvent.gigaRoot.toString()}`);

		try {
			// Get local root data for this gigaRoot
			const localRootData = await getLocalRootData(
				gigaBridgeClient,
				gigaBridgeAddresses.GigaBridge,
				localRootProviderAddress,
				gigaBridgeChainId,
				gigaRootEvent.gigaRoot
			);

			console.log(`[findGigaRootWithCommitment] Found local root: ${localRootData.localRoot.toString()} at index ${localRootData.localRootIndex}`);

			// Check if this local root contains our commitment
			const hasCommitment = await checkCommitmentInLocalRoot(
				sourceClient,
				sourceWarpToadAddress,
				commitment,
				sourceChainId,
				localRootData.localRootBlockNumber
			);

			if (hasCommitment) {
				console.log(`[findGigaRootWithCommitment] ✓ Found gigaRoot containing commitment!`);
				return {
					gigaRoot: gigaRootEvent.gigaRoot,
					localRoot: localRootData.localRoot,
					localRootIndex: localRootData.localRootIndex,
					localRootBlockNumber: localRootData.localRootBlockNumber,
					gigaRootBlockNumber: localRootData.gigaRootBlockNumber
				};
			}

			console.log(`[findGigaRootWithCommitment] Commitment not in this local root, trying next gigaRoot...`);
		} catch (error) {
			console.log(`[findGigaRootWithCommitment] Error checking gigaRoot: ${error}`);
			// Continue to next gigaRoot
			continue;
		}
	}

	// No gigaRoot found containing the commitment
	throw new Error(
		`Could not find a gigaRoot containing your commitment. This usually means:\n` +
		`1. The L2→L1 message has not been relayed yet (Scroll takes 30min-3hrs)\n` +
		`2. The relayer has not updated the gigaRoot after your L2→L1 message arrived\n` +
		`3. The gigaRoot has not been sent to Aztec yet\n\n` +
		`Please wait 1-3 hours after your burn transaction and try again.\n` +
		`Commitment: ${commitment.toString()}\n` +
		`Source Chain: ${sourceChainId}`
	);
}

/**
 * Find the Aztec block number where a specific gigaRoot was/is stored.
 * For now, checks if the gigaRoot is the current one and returns current block.
 * TODO: In future, search backwards through historical blocks to find exact block.
 * 
 * @param aztecWallet - Aztec wallet to query contract
 * @param targetGigaRoot - The gigaRoot value to find
 * @returns Aztec block number where this gigaRoot can be read
 */
async function getAztecBlockNumberForGigaRoot(
	aztecWallet: Wallet,
	targetGigaRoot: bigint
): Promise<number> {
	const aztecNode = await getAztecNode();
	const contract = await getWarpToadContract(aztecWallet);
	const accounts = await aztecWallet.getAccounts();
	const from = accounts[0].item;

	// Get current gigaRoot from Aztec contract.
	// v4: simulate() returns a SimulationResult wrapper { result, ... }
	const currentGigaRootSim = await contract.methods.get_giga_root().simulate({ from }) as any;
	const currentGigaRoot = currentGigaRootSim?.result ?? currentGigaRootSim;
	const currentGigaRootValue = typeof currentGigaRoot === 'bigint'
		? currentGigaRoot
		: BigInt(currentGigaRoot.toString());

	console.log(`[getAztecBlockNumberForGigaRoot] Current Aztec gigaRoot: ${currentGigaRootValue.toString()}`);
	console.log(`[getAztecBlockNumberForGigaRoot] Target gigaRoot: ${targetGigaRoot.toString()}`);

	// If target gigaRoot is current, use current block number
	if (currentGigaRootValue === targetGigaRoot) {
		const currentBlock = await aztecNode.getBlockNumber();
		console.log(`[getAztecBlockNumberForGigaRoot] Target gigaRoot is current, using block ${currentBlock}`);
		return currentBlock;
	}

	// TODO: For historical gigaRoots, binary search backwards through blocks
	// For now, throw error if not current
	throw new Error(
		`Target gigaRoot ${targetGigaRoot.toString()} is not the current gigaRoot on Aztec. ` +
		`Current gigaRoot is ${currentGigaRootValue.toString()}. ` +
		`The relayer may need to send the updated gigaRoot to Aztec. ` +
		`Please wait 30 minutes and try again.`
	);
}

// =============================================================================
// MERKLE DATA GENERATION
// =============================================================================

/**
 * Get EVM merkle proof for a commitment in the L1WarpToad tree
 */
async function getEvmMerkleData(
	publicClient: PublicClient,
	warpToadAddress: string,
	commitment: bigint,
	chainId: number,
	localRootBlockNumber: number,
	expectedLocalRoot: bigint
): Promise<EvmMerkleData> {
	// Get all burn events up to the local root block
	const burnEvents = await getBurnEvents(
		publicClient,
		warpToadAddress,
		chainId,
		BigInt(localRootBlockNumber)
	);

	if (burnEvents.length === 0) {
		throw new Error('No burn events found');
	}

	// Build sorted leaves array by index
	const sortedLeaves: bigint[] = [];
	let commitmentIndex = -1;

	for (const event of burnEvents) {
		sortedLeaves[event.index] = event.commitment;
		if (event.commitment === commitment) {
			commitmentIndex = event.index;
		}
	}

	if (commitmentIndex === -1) {
		throw new Error(
			`Commitment ${commitment} not found in burn events up to block ${localRootBlockNumber}. ` +
			'Either the commitment has not been bridged yet, or an incorrect block number was used.'
		);
	}

	// Fill gaps with zeros
	for (let i = 0; i < sortedLeaves.length; i++) {
		if (sortedLeaves[i] === undefined) {
			sortedLeaves[i] = 0n;
		}
	}

	// Build merkle tree and get proof using fixed-merkle-tree
	const tree = createPoseidonMerkleTree(EVM_TREE_DEPTH, sortedLeaves);

	// Validate the recreated tree root matches the expected local root
	const computedRoot = BigInt(tree.root);
	console.log('EVM tree - computed root:', computedRoot.toString());
	console.log('EVM tree - expected local root:', expectedLocalRoot.toString());

	if (computedRoot !== expectedLocalRoot) {
		throw new Error(
			`Could not recreate the localRoot with events. ` +
			`Computed: ${computedRoot}, Expected: ${expectedLocalRoot}. ` +
			`This may indicate missing burn events or an incorrect block number.`
		);
	}

	const proof = getMerkleProof(tree, commitment);

	return {
		leaf_index: BigInt(proof.leafIndex),
		hash_path: proof.pathElements,
	};
}

/**
 * Get Giga merkle proof for a local root in the GigaBridge tree
 */
async function getGigaMerkleData(
	publicClient: PublicClient,
	gigaBridgeAddress: string,
	localRoot: bigint,
	localRootIndex: number,
	chainId: number,
	gigaRootBlockNumber: number,
	expectedGigaRoot: bigint
): Promise<EvmMerkleData> {
	// Get all local root events up to the giga root block
	console.log(`[getGigaMerkleData] Querying localRoot events on chain ${chainId} up to block ${gigaRootBlockNumber}`);
	console.log(`[getGigaMerkleData] Looking for localRoot: ${localRoot.toString()} at index ${localRootIndex}`);
	
	const localRootEvents = await getLocalRootEvents(
		publicClient,
		gigaBridgeAddress,
		chainId,
		BigInt(gigaRootBlockNumber)
	);

	console.log(`[getGigaMerkleData] Found ${localRootEvents.length} localRoot events`);
	
	if (localRootEvents.length === 0) {
		throw new Error(
			`No local root events found when querying GigaBridge on chain ${chainId} ` +
			`from deployment block to block ${gigaRootBlockNumber}. ` +
			`This may indicate a rate limit error or incorrect chain/block parameters.`
		);
	}

	// Group events by index and get the latest for each
	const eventsPerIndex: Record<number, typeof localRootEvents> = {};
	const allIndexes = new Set<number>();

	for (const event of localRootEvents) {
		allIndexes.add(event.index);
		if (!eventsPerIndex[event.index]) {
			eventsPerIndex[event.index] = [];
		}
		eventsPerIndex[event.index].push(event);
	}

	// Build sorted leaves with latest root for each index
	const sortedLeaves: bigint[] = [];
	for (const index of Array.from(allIndexes).sort((a, b) => a - b)) {
		if (eventsPerIndex[index] && eventsPerIndex[index].length > 0) {
			// Get latest event for this index
			const latestEvent = eventsPerIndex[index].reduce((latest, ev) =>
				ev.eventBlockNumber > latest.eventBlockNumber ? ev : latest
			);
			sortedLeaves[index] = latestEvent.localRoot;
		} else {
			sortedLeaves[index] = 0n;
		}
	}

	// Verify local root is in tree
	if (!sortedLeaves.includes(localRoot)) {
		throw new Error(
			`Local root ${localRoot} not found in giga tree at block ${gigaRootBlockNumber}`
		);
	}

	// Build merkle tree and get proof using fixed-merkle-tree
	const tree = createPoseidonMerkleTree(GIGA_TREE_DEPTH, sortedLeaves);

	// Validate the recreated giga tree root matches the expected gigaRoot
	const computedGigaRoot = BigInt(tree.root);
	console.log('Giga tree - computed root:', computedGigaRoot.toString());
	console.log('Giga tree - expected gigaRoot:', expectedGigaRoot.toString());
	console.log('Giga tree - sorted leaves:', sortedLeaves.map(l => l.toString()));

	if (computedGigaRoot !== expectedGigaRoot) {
		throw new Error(
			`Could not recreate the gigaRoot with events. ` +
			`Computed: ${computedGigaRoot}, Expected: ${expectedGigaRoot}. ` +
			`This may indicate missing local root events or an incorrect block number.`
		);
	}

	const proof = getMerkleProof(tree, localRoot);

	return {
		leaf_index: BigInt(localRootIndex),
		hash_path: proof.pathElements,
	};
}

/**
 * Get local root data from GigaBridge events for a specific gigaRoot
 * 
 * This function finds the transaction where the specific gigaRoot was constructed,
 * then extracts the local root data from the ReceivedNewLocalRoot events in that transaction.
 * 
 * @param gigaRoot - The specific gigaRoot value to find (from the Aztec contract)
 */
async function getLocalRootData(
	publicClient: PublicClient,
	gigaBridgeAddress: string,
	localRootProviderAddress: string,
	chainId: number,
	gigaRoot: bigint
): Promise<LocalRootData> {
	const localRootIndexRaw = await publicClient.readContract({
		address: gigaBridgeAddress as `0x${string}`,
		abi: GigaBridgeAbi,
		functionName: 'getLocalRootProvidersIndex',
		args: [localRootProviderAddress as `0x${string}`],
	});
	const localRootIndex = Number(localRootIndexRaw);
	console.log(`Local root provider ${localRootProviderAddress} index: ${localRootIndex}`);

	const gigaRootEvents = await getGigaRootEvents(publicClient, gigaBridgeAddress, chainId, gigaRoot);
	if (gigaRootEvents.length === 0) {
		throw new Error(
			`GigaRoot ${gigaRoot} not found in L1 events. ` +
			'The bridge state may be inconsistent, or the gigaRoot was constructed on a different chain.'
		);
	}

	const gigaRootEvent = gigaRootEvents[gigaRootEvents.length - 1];
	const gigaRootBlockNumber = Number(gigaRootEvent.blockNumber);
	console.log(`Found ConstructedNewGigaRoot event at L1 block ${gigaRootBlockNumber}, tx: ${gigaRootEvent.transactionHash}`);

	// Walk events backward from the gigaRoot construction block. The provider's
	// local root may have been last updated many blocks earlier - if we only
	// look at events in the construction block we miss it for any provider
	// that wasn't part of that updateGigaRoot call.
	const matchingEvent = await getLatestLocalRootEventForIndex(
		publicClient,
		gigaBridgeAddress,
		chainId,
		localRootIndex,
		gigaRootEvent.blockNumber
	);

	if (!matchingEvent) {
		throw new Error(
			`No ReceivedNewLocalRoot event found for index ${localRootIndex} (provider ${localRootProviderAddress}) ` +
			`at or before block ${gigaRootBlockNumber}. The provider may never have been updated.`
		);
	}

	console.log(`Matched local root for index ${localRootIndex}: ${matchingEvent.localRoot} (last updated at L1 block ${matchingEvent.eventBlockNumber})`);

	return {
		localRoot: matchingEvent.localRoot,
		localRootIndex,
		localRootBlockNumber: matchingEvent.blockNumber,
		gigaRootBlockNumber,
	};
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get L1 chain ID based on environment
 * For Scroll L2, GigaBridge lives on L1 (Sepolia or Localhost)
 */
function getL1ChainId(): number {
	// In test mode: localhost (31337)
	// In testnet mode: Sepolia (11155111)
	const isTestMode = import.meta.env.VITE_TEST_MODE === 'true';
	return isTestMode ? 31337 : 11155111;
}

/**
 * Determine which chain has the GigaBridge for a given source chain
 * - L1 chains (31337, 11155111): GigaBridge is on same chain
 * - L2 chains (534351 Scroll): GigaBridge is on L1
 */
function getGigaBridgeChainId(sourceChainId: number): number {
	// Scroll Sepolia (534351) -> GigaBridge is on L1 (Sepolia/Localhost)
	if (sourceChainId === 534351) {
		return getL1ChainId();
	}
	// L1 chains have GigaBridge on same chain
	return sourceChainId;
}

// =============================================================================
// MAIN MERKLE DATA FUNCTION
// =============================================================================

/**
 * Get all merkle data needed for minting on Aztec
 * 
 * @param sourceChainId - The chain ID where the burn happened (e.g., 31337 for anvil, 534351 for Scroll)
 * @param commitment - The commitment hash from the burn
 * @param gigaRoot - The specific gigaRoot value from the Aztec contract (ensures consistency)
 * @returns Merkle data for the mint transaction
 */
export async function getMerkleData(
	sourceChainId: number,
	commitment: bigint,
	gigaRoot: bigint
): Promise<MerkleDataResult> {
	console.log(`[getMerkleData] Source chain: ${sourceChainId}`);
	
	const addresses = getContractAddresses(sourceChainId);

	// Use L2WarpToad for Scroll (534351), L1WarpToad for other chains
	const warpToadAddress = addresses.L2WarpToad || addresses.L1WarpToad;
	
	if (!warpToadAddress) {
		throw new Error(`WarpToad address not found for chain ${sourceChainId}`);
	}
	
	// For Scroll L2, GigaBridge lives on L1, not on Scroll itself
	const gigaBridgeChainId = getGigaBridgeChainId(sourceChainId);
	console.log(`[getMerkleData] GigaBridge chain: ${gigaBridgeChainId}`);
	
	const gigaBridgeAddresses = getContractAddresses(gigaBridgeChainId);
	if (!gigaBridgeAddresses.GigaBridge) {
		throw new Error(`GigaBridge address not found for chain ${gigaBridgeChainId}`);
	}

	// Determine the correct local root provider address for GigaBridge queries
	// The provider is the address that registered roots with GigaBridge
	let localRootProviderAddress: string;
	
	if (sourceChainId === 534351) {
		// For Scroll: Use L1ScrollBridgeAdapter (the provider registered with GigaBridge)
		// Architecture: Scroll L2WarpToad → L2ScrollBridgeAdapter → L1ScrollBridgeAdapter → GigaBridge
		if (!gigaBridgeAddresses.L1ScrollBridgeAdapter) {
			throw new Error(`L1ScrollBridgeAdapter address not found for chain ${gigaBridgeChainId}`);
		}
		localRootProviderAddress = gigaBridgeAddresses.L1ScrollBridgeAdapter;
		console.log(`[getMerkleData] Using L1ScrollBridgeAdapter as local root provider: ${localRootProviderAddress}`);
	} else {
		// For L1 chains: Use L1WarpToad directly
		if (!gigaBridgeAddresses.L1WarpToad) {
			throw new Error(`L1WarpToad address not found for chain ${gigaBridgeChainId}`);
		}
		localRootProviderAddress = gigaBridgeAddresses.L1WarpToad;
		console.log(`[getMerkleData] Using L1WarpToad as local root provider: ${localRootProviderAddress}`);
	}

	// Create clients for both source chain (for burn events) and GigaBridge chain
	const sourceClient = createEvmClient(sourceChainId);
	const gigaBridgeClient = createEvmClient(gigaBridgeChainId);

	// Step 1: Get local root data
	// For Scroll: Find a gigaRoot that contains the commitment (may differ from Aztec's current gigaRoot)
	// For L1: Use the gigaRoot from Aztec contract directly
	let localRootData: LocalRootData;
	let actualGigaRoot: bigint;

	if (sourceChainId === 534351) {
		// Scroll case: Find ANY gigaRoot on L1 that contains our commitment
		console.log('[getMerkleData] Scroll detected - searching for gigaRoot containing commitment...');
		const foundData = await findGigaRootWithCommitment(
			sourceChainId,
			commitment,
			warpToadAddress
		);
		
		actualGigaRoot = foundData.gigaRoot;
		localRootData = {
			localRoot: foundData.localRoot,
			localRootIndex: foundData.localRootIndex,
			localRootBlockNumber: foundData.localRootBlockNumber,
			gigaRootBlockNumber: foundData.gigaRootBlockNumber
		};
		
		console.log(`[getMerkleData] Found gigaRoot: ${actualGigaRoot.toString()}`);
		console.log(`[getMerkleData] Local root: ${localRootData.localRoot.toString()}`);
		console.log(`[getMerkleData] GigaRoot block number: ${localRootData.gigaRootBlockNumber}`);
	} else {
		// L1 case: Use gigaRoot from Aztec contract (traditional flow)
		console.log('[getMerkleData] L1 chain - using gigaRoot from Aztec:', gigaRoot.toString());
		actualGigaRoot = gigaRoot;
		localRootData = await getLocalRootData(
			gigaBridgeClient,
			gigaBridgeAddresses.GigaBridge!,
			localRootProviderAddress,
			sourceChainId,
			gigaRoot
		);
		console.log('Local root data:', localRootData);
	}

	// Step 2: Get EVM merkle proof (commitment in local root)
	// This queries the source chain (L1 or Scroll) for burn events
	console.log('Building EVM merkle proof...');
	const evmMerkleData = await getEvmMerkleData(
		sourceClient,
		warpToadAddress,
		commitment,
		sourceChainId,
		localRootData.localRootBlockNumber,
		localRootData.localRoot
	);
	console.log('EVM merkle proof built');

	// Step 3: Get Giga merkle proof (local root in giga root)
	// This queries GigaBridge (on L1) to prove local root is in gigaRoot
	console.log('Building Giga merkle proof...');
	const gigaMerkleData = await getGigaMerkleData(
		gigaBridgeClient,
		gigaBridgeAddresses.GigaBridge!,
		localRootData.localRoot,
		localRootData.localRootIndex,
		gigaBridgeChainId,
		localRootData.gigaRootBlockNumber,
		actualGigaRoot  // Use the actual gigaRoot we're building proofs against
	);
	console.log('Giga merkle proof built');

	// Step 4: Get Aztec block number for historical state read
	// For L1: Use current block number (traditional flow)
	// For Scroll: We need to return the actualGigaRoot so mintFromEVM can find its block number
	const aztecNode = await getAztecNode();
	const blockNumber = await aztecNode.getBlockNumber();

	console.log(`Using Aztec block ${blockNumber} for historical read`);

	return {
		blockNumber,
		originLocalRoot: localRootData.localRoot,
		gigaMerkleData,
		evmMerkleData,
		actualGigaRoot,  // Return the gigaRoot we actually used (may differ from parameter)
	};
}

// =============================================================================
// AZTEC BALANCE
// =============================================================================

/**
 * Get the WarpToad token balance for the connected Aztec wallet
 */
export async function getAztecWarpToadBalance(wallet: Wallet): Promise<bigint> {
	const contract = await getWarpToadContract(wallet);
	const accounts = await wallet.getAccounts();
	const ownerAddress = accounts[0].item;

	// Call the unconstrained balance_of function.
	// v4: simulate() returns a SimulationResult wrapper { result, ... }
	const balanceSim = await contract.methods.balance_of(ownerAddress).simulate({ from: ownerAddress }) as any;
	const balance = balanceSim?.result ?? balanceSim;

	console.log('Aztec WarpToad Balance:', balance.toString());
	return BigInt(balance.toString());
}

/**
 * Get the WarpToad token decimals from the Aztec contract
 */
export async function getAztecWarpToadDecimals(wallet: Wallet): Promise<number> {
	const contract = await getWarpToadContract(wallet);
	const accounts = await wallet.getAccounts();
	const from = accounts[0].item;

	// v4: simulate() returns a SimulationResult wrapper { result, ... }
	const decimalsSim = await contract.methods.get_decimals().simulate({ from }) as any;
	const decimals = decimalsSim?.result ?? decimalsSim;
	return Number(decimals);
}

// =============================================================================
// AZTEC CHAIN ID
// =============================================================================

/**
 * Get Aztec chain ID from the WarpToad contract
 * Aztec uses: poseidon2([salt, aztec_version]) where salt is "aztecPlsJustPickAChainId"
 */
export async function getAztecChainId(aztecWallet: Wallet): Promise<bigint> {
	const contract = await getWarpToadContract(aztecWallet);
	const accounts = await aztecWallet.getAccounts();
	const from = accounts[0].item;

	// In v4 .simulate() returns a SimulationResult wrapper; the actual return
	// value is on `.result`.
	const versionSim = await contract.methods.get_version().simulate({ from }) as any;
	const version = versionSim.result ?? versionSim;

	const chainIdSim = await contract.methods.get_chain_id_unconstrained(version).simulate({ from }) as any;
	const chainId = chainIdSim.result ?? chainIdSim;

	return BigInt(chainId.toString());
}

// =============================================================================
// VALIDATION
// =============================================================================

/**
 * Validate that a commitment exists in the WarpToad burn events
 */
export async function validateCommitmentExists(
	commitment: bigint,
	sourceChainId: number
): Promise<boolean> {
	try {
		const addresses = getContractAddresses(sourceChainId);
		
		// Use L2WarpToad for Scroll (534351), L1WarpToad for other chains
		const warpToadAddress = addresses.L2WarpToad || addresses.L1WarpToad;
		
		if (!warpToadAddress) {
			return false;
		}

		const publicClient = createEvmClient(sourceChainId);

		// Use deployment block to avoid scanning entire blockchain history
		const fromBlock = getDeploymentBlock(sourceChainId);

		console.log(`[validateCommitmentExists] Scanning for commitment ${commitment.toString()} from block ${fromBlock} to latest on chain ${sourceChainId}`);

		// Burn is emitted once per commitment - scan backwards and stop at first hit.
		const abi = addresses.L2WarpToad ? L2WarpToadAbi : L1WarpToadAbi;
		const logs = await queryEventInChunks({
			publicClient,
			contract: { address: warpToadAddress as `0x${string}`, abi },
			eventName: 'Burn',
			eventFilterArgs: { commitment },
			firstBlock: fromBlock,
			reverseOrder: true,
			maxEvents: 1,
		});

		console.log(`[validateCommitmentExists] Found ${logs.length} matching Burn events`);

		return logs.length > 0;
	} catch (error) {
		console.error('Error validating commitment:', error);
		return false;
	}
}

/**
 * Check if the GigaRoot has been synced to Aztec and return its value
 * @returns The gigaRoot value if synced (non-zero), null if not synced or error
 */
export async function getAztecGigaRoot(aztecWallet: Wallet): Promise<bigint | null> {
	try {
		const contract = await getWarpToadContract(aztecWallet);
		const accounts = await aztecWallet.getAccounts();
		const from = accounts[0].item;

		// v4: simulate() returns a SimulationResult wrapper { result, ... }; the
		// actual return value is on `.result`. Older versions returned the bare
		// value, so accept both shapes.
		const sim = await contract.methods.get_giga_root().simulate({ from }) as any;
		const gigaRoot = sim?.result ?? sim;

		// Convert Fr/Field object to bigint for proper comparison
		const gigaRootValue = typeof gigaRoot === 'bigint'
			? gigaRoot
			: BigInt(gigaRoot.toString());

		console.log('GigaRoot from Aztec contract:', gigaRootValue.toString());

		// Return null if gigaRoot is 0 (not synced)
		if (gigaRootValue === 0n) {
			return null;
		}

		return gigaRootValue;
	} catch (error) {
		console.error('Error getting giga root from Aztec:', error);
		return null;
	}
}

/**
 * Check if the GigaRoot has been synced to Aztec (convenience wrapper)
 */
export async function validateGigaRootSynced(aztecWallet: Wallet): Promise<boolean> {
	const gigaRoot = await getAztecGigaRoot(aztecWallet);
	return gigaRoot !== null;
}

/**
 * Result of nullifier check
 */
export interface NullifierCheckResult {
	/** Whether the nullifier has been spent */
	isSpent: boolean;
	/** Whether the check was successful (could connect to node) */
	success: boolean;
	/** Error message if check failed */
	error?: string;
}

/**
 * Check if a nullifier has been spent on Aztec
 * 
 * This queries the Aztec node's nullifier tree to check if a nullifier exists.
 * If the nullifier exists in the tree, it means the note has already been withdrawn.
 * 
 * IMPORTANT: Aztec siloes nullifiers before storing them in the tree.
 * The siloed nullifier = poseidon2([contract_address, inner_nullifier], GENERATOR_INDEX.OUTER_NULLIFIER)
 * 
 * @param siloedNullifier - The siloed nullifier (already processed with contract address)
 * @returns NullifierCheckResult with isSpent status and success/error info
 */
export async function isNullifierSpent(siloedNullifier: Fr): Promise<NullifierCheckResult> {
	try {
		const aztecNode = await getAztecNode();

		// Query the nullifier tree to check if this nullifier exists
		// Using findLeavesIndexes with NULLIFIER_TREE is the correct way to check existence
		// If the nullifier is found (index !== undefined), it has been spent
		const [nullifierIndex] = await aztecNode.findLeavesIndexes(
			'latest',
			MerkleTreeId.NULLIFIER_TREE,
			[siloedNullifier]
		);

		const isSpent = nullifierIndex !== undefined;
		console.log(`Siloed nullifier ${siloedNullifier.toString().slice(0, 20)}... spent: ${isSpent}`);

		return { isSpent, success: true };
	} catch (error) {
		console.error('Error checking nullifier status:', error);
		const errorMessage = error instanceof Error ? error.message : 'Unknown error';

		// Check if it's a connection error
		if (errorMessage.includes('connect') || errorMessage.includes('ECONNREFUSED') || errorMessage.includes('fetch')) {
			return {
				isSpent: false,
				success: false,
				error: 'Could not connect to Aztec node. Make sure the sandbox is running.'
			};
		}

		return {
			isSpent: false,
			success: false,
			error: `Failed to check nullifier: ${errorMessage}`
		};
	}
}

/**
 * Check if a note has already been used/withdrawn on Aztec
 * 
 * This function:
 * 1. Computes the inner nullifier from the preimage: poseidon1([nullifier_preimage])
 * 2. Siloes it with the WarpToad contract address: poseidon2([contract, nullifier], OUTER_NULLIFIER)
 * 3. Looks up the siloed nullifier in the Aztec nullifier tree
 * 
 * @param nullifierPreimage - The nullifier preimage from the note data
 * @returns NullifierCheckResult with isSpent status and success/error info
 */
export async function isNoteUsed(nullifierPreimage: bigint): Promise<NullifierCheckResult> {
	try {
		// Step 1: Compute inner nullifier (same as Noir circuit)
		const innerNullifier = hashNullifier(nullifierPreimage);
		const innerNullifierFr = Fr.fromString(innerNullifier.toString());

		// Step 2: Get the WarpToad contract address
		const warpToadAddressStr = AZTEC_CONTRACTS.AztecWarpToad.address;
		if (!warpToadAddressStr) {
			return {
				isSpent: false,
				success: false,
				error: 'WarpToad contract address not configured'
			};
		}
		const warpToadAddress = AztecAddress.fromString(warpToadAddressStr);

		// Step 3: Silo the nullifier with the contract address
		// This matches what Aztec does internally when context.push_nullifier() is called
		const siloedNullifier = await siloNullifier(warpToadAddress, innerNullifierFr);

		console.log(`Inner nullifier: ${innerNullifier.toString().slice(0, 20)}...`);
		console.log(`WarpToad address: ${warpToadAddress.toString()}`);
		console.log(`Siloed nullifier: ${siloedNullifier.toString().slice(0, 20)}...`);

		// Step 4: Check if siloed nullifier exists in the tree
		return isNullifierSpent(siloedNullifier);
	} catch (error) {
		console.error('Error in isNoteUsed:', error);
		const errorMessage = error instanceof Error ? error.message : 'Unknown error';
		return {
			isSpent: false,
			success: false,
			error: `Failed to check note status: ${errorMessage}`
		};
	}
}

// =============================================================================
// MINT FROM EVM (MAIN WITHDRAW FUNCTION)
// =============================================================================


/**
 * Little sanity check for merkle root compute
 */
function computeMerkleRootFromPath(
	leaf: bigint,
	leafIndex: bigint,
	hashPath: bigint[],
): bigint {
	let acc = leaf;
	let index = leafIndex;

	for (const sibling of hashPath) {
		if ((index & 1n) === 0n) {
			// leaf is on the left

			acc = poseidon2([acc, sibling]); // same hash + ordering as Noir
		} else {
			// leaf is on the right
			acc = poseidon2([sibling, acc]);
		}
		index >>= 1n;
	}

	return acc;
}



/**
 * Mint tokens on Aztec from an L1 burn commitment
 * 
 * This is the main withdraw function that:
 * 1. Gets the current gigaRoot from Aztec to ensure proof consistency
 * 2. Builds merkle proofs for the commitment against that specific gigaRoot
 * 3. Calls mint_giga_root_evm on the Aztec WarpToad contract
 * 
 * @param wallet - Connected Aztec wallet (in-browser BrowserEmbeddedWallet)
 * @param commitmentData - The commitment pre-image (secret, nullifier_preimg, amount, chain_id)
 * @param sourceChainId - The L1 chain ID where the burn happened
 * @param recipientAddress - Aztec address to receive the tokens
 * @param gigaRoot - The gigaRoot value from Aztec contract (from getAztecGigaRoot)
 * @returns Transaction hash
 */
export async function mintFromEVM(
	wallet: Wallet,
	commitmentData: CommitmentPreImage,
	sourceChainId: number,
	recipientAddress: string,
	gigaRoot: bigint
): Promise<string> {
	console.log('Starting mintFromEVM...');
	console.log('Commitment data:', {
		amount: commitmentData.amount.toString(),
		destination_chain_id: commitmentData.destination_chain_id.toString(),
	});
	console.log('Using gigaRoot from Aztec:', gigaRoot.toString());

	// Get the WarpToad contract
	const contract = await getWarpToadContract(wallet);
	const accounts = await wallet.getAccounts();
	const from = accounts[0].item;

	// Step 1: Calculate commitment hash
	const preCommitment = hashPreCommitment(
		commitmentData.nullifier_preimg,
		commitmentData.secret,
		commitmentData.destination_chain_id
	);
	const commitment = hashCommitment(preCommitment, commitmentData.amount);
	console.log('Calculated commitment:', commitment.toString());

	// Step 2: Get merkle data using the specific gigaRoot from Aztec
	// This ensures the proofs are built against the exact gigaRoot stored on Aztec
	console.log('Getting merkle data...');
	const merkleData = await getMerkleData(sourceChainId, commitment, gigaRoot);
	console.log('Merkle data retrieved:', merkleData);

	const evmRootFromPath = computeMerkleRootFromPath(
		commitment,
		BigInt(merkleData.evmMerkleData.leaf_index),
		merkleData.evmMerkleData.hash_path.map(BigInt),
	);

	console.log('[mintFromEVM] EVM path recomputed root matches? :', evmRootFromPath.toString() === merkleData.originLocalRoot.toString());

	const gigaRootFromPath = computeMerkleRootFromPath(
		merkleData.originLocalRoot,
		BigInt(merkleData.gigaMerkleData.leaf_index),
		merkleData.gigaMerkleData.hash_path.map(BigInt),
	);

	// For Scroll, merkleData.actualGigaRoot may differ from the gigaRoot parameter
	const expectedGigaRoot = merkleData.actualGigaRoot || gigaRoot;
	console.log('[mintFromEVM] Giga path recomputed root matches? :', gigaRootFromPath.toString() === expectedGigaRoot.toString());

	console.log('[mintFromEVM] Raw merkleData:', {
		blockNumber: merkleData.blockNumber,
		originLocalRoot: merkleData.originLocalRoot.toString(),
		gigaMerkleData: {
			leaf_index: merkleData.gigaMerkleData.leaf_index.toString(),
			hash_path: merkleData.gigaMerkleData.hash_path.map(x => x.toString()),
		},
		evmMerkleData: {
			leaf_index: merkleData.evmMerkleData.leaf_index.toString(),
			hash_path: merkleData.evmMerkleData.hash_path.map(x => x.toString()),
		},
	});

	// Step 3: Prepare recipient address
	const recipient = AztecAddress.fromString(recipientAddress);

	// Step 3.5: For Scroll, find the Aztec block number where actualGigaRoot is stored
	// For L1, use the blockNumber from merkleData
	let aztecBlockNumber: number;
	if (merkleData.actualGigaRoot) {
		console.log('[mintFromEVM] Scroll flow detected - finding Aztec block for gigaRoot:', merkleData.actualGigaRoot.toString());
		aztecBlockNumber = await getAztecBlockNumberForGigaRoot(wallet, merkleData.actualGigaRoot);
		console.log('[mintFromEVM] Found Aztec block number:', aztecBlockNumber);
	} else {
		aztecBlockNumber = merkleData.blockNumber;
		console.log('[mintFromEVM] L1 flow - using block number from merkleData:', aztecBlockNumber);
	}

	// Step 4: Format merkle data for Aztec contract
	// The Aztec contract expects Evm_merkle_data<D> which has { leaf_index: Field, hash_path: [Field; D] }
	const gigaMerkleDataFormatted = {
		leaf_index: merkleData.gigaMerkleData.leaf_index,
		hash_path: merkleData.gigaMerkleData.hash_path,
	};

	const evmMerkleDataFormatted = {
		leaf_index: merkleData.evmMerkleData.leaf_index,
		hash_path: merkleData.evmMerkleData.hash_path,
	};

	console.log('Calling mint_giga_root_evm...');
	console.log('Parameters:', {
		amount: commitmentData.amount.toString(),
		secret: commitmentData.secret.toString().slice(0, 10) + '...',
		nullifier_preimage: commitmentData.nullifier_preimg.toString().slice(0, 10) + '...',
		recipient: recipient.toString(),
		block_number: aztecBlockNumber,
		origin_local_root: merkleData.originLocalRoot.toString(),
	});

	console.log('[mintFromEVM] Expected relationships:', {
		// Noir checks: commit -> originLocalRoot
		commitment: commitment.toString(),
		originLocalRoot: merkleData.originLocalRoot.toString(),

		// Noir checks: originLocalRoot -> gigaRoot
		gigaRoot: expectedGigaRoot.toString(),

		// Historical read in Noir:
		aztecBlockNumber: aztecBlockNumber,
	});


	console.log("\n")

	// Step 5: Call mint_giga_root_evm
	// Function signature from Noir:
	// fn mint_giga_root_evm(
	//     amount: u64,
	//     secret: Field,
	//     nullifier_preimage: Field,
	//     recipient: AztecAddress,
	//     block_number: u32,
	//     origin_local_root: Field,
	//     giga_merkle_data: Evm_merkle_data<GIGA_TREE_DEPTH>,
	//     evm_merkle_data: Evm_merkle_data<EVM_TREE_DEPTH>,
	// )
	// v4: .send() returns a Promise that already resolves to the receipt; no .wait() needed.
	// Pay fees via the sponsored FPC (registered during wallet connect). Without it,
	// the tx is rejected with "Insufficient fee payer balance" because the test
	// account has no fee juice on the sandbox.
	const sponsoredPaymentMethod = getSponsoredPaymentMethod();
	const tx = await contract.methods.mint_giga_root_evm(
		commitmentData.amount,           // amount: u64
		commitmentData.secret,           // secret: Field
		commitmentData.nullifier_preimg, // nullifier_preimage: Field
		recipient,                       // recipient: AztecAddress
		aztecBlockNumber,                // block_number: u32 (correct block for historical read)
		merkleData.originLocalRoot,      // origin_local_root: Field
		gigaMerkleDataFormatted,         // giga_merkle_data
		evmMerkleDataFormatted,          // evm_merkle_data
	).send({
		from,
		...(sponsoredPaymentMethod ? { fee: { paymentMethod: sponsoredPaymentMethod } } : {}),
	});

	// v4 result shape: tx.receipt.txHash (the receipt is already mined since
	// .send() now waits internally).
	console.log('Mint transaction completed:', tx.receipt.txHash.toString());
	return tx.receipt.txHash.toString();
}

// =============================================================================
// BALANCE CHECKING
// =============================================================================

/**
 * Get token balance on Aztec WarpToad
 */
export async function getAztecBalance(
	wallet: Wallet,
	ownerAddress?: string
): Promise<bigint> {
	const contract = await getWarpToadContract(wallet);
	const accounts = await wallet.getAccounts();
	const from = accounts[0].item;

	const owner = ownerAddress
		? AztecAddress.fromString(ownerAddress)
		: from;

	// Note: balance_of is an unconstrained function, uses 'from' for simulation context.
	// v4: simulate() returns a SimulationResult wrapper { result, ... }
	const balanceSim = await contract.methods.balance_of(owner).simulate({ from }) as any;
	const balance = balanceSim?.result ?? balanceSim;
	return BigInt(balance.toString());
}

// =============================================================================
// AZTEC -> L1 BRIDGING (BURN ON AZTEC)
// =============================================================================

// Field size for BN254 curve (used by Aztec)
const FIELD_MODULUS = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;

/**
 * Generate cryptographically secure random field element
 */
function generateRandomField(): bigint {
	const randomBytes = new Uint8Array(32);
	crypto.getRandomValues(randomBytes);

	let value = 0n;
	for (let i = 0; i < randomBytes.length; i++) {
		value = (value << 8n) | BigInt(randomBytes[i]);
	}

	return value % FIELD_MODULUS;
}

/**
 * Burn tokens on Aztec to initiate a withdrawal to L1
 * 
 * This function:
 * 1. Generates random secret and nullifier preimage
 * 2. Computes the commitment hash
 * 3. Calls the Aztec WarpToadCore.burn() function
 * 4. Returns the commitment data needed for L1 withdrawal
 * 
 * @param wallet - Connected Aztec wallet
 * @param amount - Amount to burn (in token's smallest units)
 * @param destinationChainId - The L1 chain ID where tokens will be claimed
 * @returns Burn result with commitment data
 */
export async function burnOnAztec(
	wallet: Wallet,
	amount: bigint,
	destinationChainId: bigint
): Promise<AztecBurnResult> {
	console.log('Starting burnOnAztec...');
	console.log('Amount:', amount.toString());
	console.log('Destination chain ID:', destinationChainId.toString());

	const contract = await getWarpToadContract(wallet);
	const accounts = await wallet.getAccounts();
	const from = accounts[0].item;

	// Step 1: Generate random secret and nullifier preimage
	const secret = generateRandomField();
	const nullifierPreimage = generateRandomField();
	console.log('Generated secret and nullifier preimage');

	// Step 2: Compute pre-commitment hash
	// preCommitment = poseidon3([nullifier_preimage, secret, destination_chain_id])
	const preCommitment = hashPreCommitment(nullifierPreimage, secret, destinationChainId);
	console.log('Pre-commitment:', preCommitment.toString().slice(0, 20) + '...');

	// Step 3: Compute full commitment hash
	// commitment = poseidon2([pre_commitment, amount])
	const commitment = hashCommitment(preCommitment, amount);
	console.log('Commitment:', commitment.toString().slice(0, 20) + '...');

	// Step 4: Call Aztec burn function
	// fn burn(amount: u64, destination_chain_id: Field, secret: Field, nullifier_preimage: Field)
	console.log('Calling WarpToadCore.burn()...');
	// v4: .send() returns a Promise that already resolves to the receipt; no .wait() needed.
	// Pay fees via the sponsored FPC (registered during wallet connect).
	const burnSponsoredPaymentMethod = getSponsoredPaymentMethod();
	const tx = await contract.methods.burn(
		amount,                    // amount: u64
		destinationChainId,        // destination_chain_id: Field
		secret,                    // secret: Field
		nullifierPreimage          // nullifier_preimage: Field
	).send({
		from,
		...(burnSponsoredPaymentMethod ? { fee: { paymentMethod: burnSponsoredPaymentMethod } } : {}),
	});

	// v4 result shape: tx.receipt.txHash
	console.log('Burn transaction completed:', tx.receipt.txHash.toString());

	// Get the block number when the burn was included
	const aztecNode = await getAztecNode();
	const blockNumber = await aztecNode.getBlockNumber();
	console.log('Burn included at Aztec block:', blockNumber);

	return {
		secret,
		nullifierPreimage,
		preCommitment,
		commitment,
		burnTxHash: tx.receipt.txHash.toString(),
		blockNumber,
	};
}

/**
 * Encode note for Aztec -> L1 bridge
 * Includes Aztec-specific metadata (blockNumber) for merkle proof generation
 */
export function encodeAztecNote(
	burnResult: AztecBurnResult,
	sourceChainId: bigint,
	destinationChainId: bigint,
	amount: bigint
): string {
	const noteData = {
		version: '1.0',
		protocol: 'warptoad',
		sourceChainId: sourceChainId.toString(),
		destinationChainId: destinationChainId.toString(),
		amount: amount.toString(),
		secret: burnResult.secret.toString(),
		nullifier_preimg: burnResult.nullifierPreimage.toString(),
		preCommitment: burnResult.preCommitment.toString(),
		commitment: burnResult.commitment.toString(),
		// Aztec-specific fields
		aztecBlockNumber: burnResult.blockNumber,
		burnTxHash: burnResult.burnTxHash,
	};

	const jsonStr = JSON.stringify(noteData);
	const base64 = btoa(jsonStr);

	return `warptoad-note-${base64}`;
}

// =============================================================================
// AZTEC MERKLE PROOF GENERATION (FOR AZTEC -> L1)
// =============================================================================

/**
 * Poseidon2 hash with separator (for Aztec note hashing)
 * Uses @zkpassport/poseidon2 which is compatible with Aztec's poseidon2
 */
async function poseidon2HashWithSeparator(inputs: bigint[], separator: bigint): Promise<bigint> {
	// Import dynamically since it's an async module
	//@ts-ignore
	const { poseidon2Hash } = await import('@zkpassport/poseidon2');
	const inputsWithSeparator = [separator, ...inputs];
	return poseidon2Hash(inputsWithSeparator);
}

/**
 * Compute note hash nonce (for Aztec note siloing)
 */
async function hashNoteHashNonce(firstNullifierInTx: bigint, noteIndexInTx: bigint): Promise<bigint> {
	return poseidon2HashWithSeparator([firstNullifierInTx, noteIndexInTx], GENERATOR_INDEX__NOTE_HASH_NONCE);
}

/**
 * Compute siloed note hash (contract address + plain note hash)
 */
async function hashSiloedNoteHash(contractAddress: bigint, plainNoteHash: bigint): Promise<bigint> {
	return poseidon2HashWithSeparator([contractAddress, plainNoteHash], GENERATOR_INDEX__SILOED_NOTE_HASH);
}

/**
 * Compute unique note hash (nonce + siloed note hash)
 */
async function hashUniqueNoteHash(nonce: bigint, siloedNoteHash: bigint): Promise<bigint> {
	return poseidon2HashWithSeparator([nonce, siloedNoteHash], GENERATOR_INDEX__UNIQUE_NOTE_HASH);
}

/**
 * Get Aztec merkle data for a commitment
 * 
 * This is needed for Aztec -> L1 withdrawals. The function:
 * 1. Queries the contract to find the note with matching commitment
 * 2. Gets the note's nonce from metadata
 * 3. Computes the siloed and unique note hash (as Aztec does)
 * 4. Gets the merkle proof from the note hash tree
 * 
 * @param wallet - Connected Aztec wallet
 * @param commitment - The commitment hash (plain note hash before siloing)
 * @param blockNumber - Aztec block number when the commitment was created
 * @returns Merkle data for the withdraw circuit
 */
export async function getAztecMerkleData(
	wallet: Wallet,
	commitment: bigint,
	blockNumber: number
): Promise<AztecMerkleData> {
	console.log('Getting Aztec merkle data for commitment:', commitment.toString().slice(0, 20) + '...');
	console.log('Block number:', blockNumber);

	const contract = await getWarpToadContract(wallet);
	const accounts = await wallet.getAccounts();
	const from = accounts[0].item;

	// Step 1: Get notes from the contract to find the note nonce
	// The contract has a utility function that returns notes from the commitments storage
	console.log('Fetching notes from contract...');
	// Use get_notes_with_nonces (read-only) instead of get_notes_util (which nullifies!).
	// Returns BoundedVec<{ note: WarpToadNote, note_nonce: Field }, 16>.
	const contractNotesSim = await contract.methods
		.get_notes_with_nonces(contract.artifact.storageLayout.commitments.slot)
		.simulate({ from }) as any;
	const contractNotes = contractNotesSim.result ?? contractNotesSim;

	console.log('Retrieved', contractNotes.storage.length, 'notes');

	// Step 2: Collect ALL notes matching the commitment. The same
	// (nullifier_preimage, secret, chain_id, amount) tuple can exist multiple times
	// (e.g. stale + fresh burn entries), so we gather them all and try each one's
	// unique note hash against the merkle tree, preferring the most recent first.
	const matchingNonces: bigint[] = [];
	for (const entry of contractNotes.storage) {
		const noteCommitment = hashCommitment(
			hashPreCommitment(
				BigInt(entry.note.nullifier_preimage.toString()),
				BigInt(entry.note.secret.toString()),
				BigInt(entry.note.chain_id.toString())
			),
			BigInt(entry.note.amount.toString())
		);
		if (noteCommitment === commitment) {
			matchingNonces.push(BigInt(entry.note_nonce.toString()));
		}
	}
	console.log(`Found ${matchingNonces.length} note(s) matching commitment`);
	// Try most recent first (storage order tends to be append-only, so reverse).
	matchingNonces.reverse();
	const noteNonce: bigint | null = matchingNonces[0] ?? null;

	if (noteNonce === null) {
		throw new Error(
			`Could not find note with commitment ${commitment.toString().slice(0, 20)}... ` +
			'The note may not be synced to this wallet yet, or the commitment data is incorrect.'
		);
	}

	// Step 3: Compute the siloed and unique note hash
	const warpToadAddressStr = AZTEC_CONTRACTS.AztecWarpToad.address;
	const contractAddressBigInt = BigInt(AztecAddress.fromString(warpToadAddressStr).toBigInt());

	const siloedNoteHash = await hashSiloedNoteHash(contractAddressBigInt, commitment);
	console.log('Siloed note hash:', siloedNoteHash.toString().slice(0, 20) + '...');

	// Step 4: Query the Aztec node directly for the membership witness.
	//
	// Earlier versions called `contract.methods.get_note_proof(...).simulate()`,
	// which routes through PXE's private-function simulator. That path picks
	// an "anchor block" based on PXE's local chain view and then asks the node
	// for state at `blockNumber` constrained to that anchor hash. On testnet
	// the anchor hash that PXE settles on is not always one the node will
	// recognise (proven tip drift, partial sync, etc.), producing cryptic
	// "Block hash X not found in world state at block number N" errors even
	// after a full PXE reset.
	//
	// `aztecNode.getNoteHashMembershipWitness` skips PXE entirely: the node
	// computes the witness against its own canonical view of `blockNumber`.
	// Returns undefined when the leaf isn't in the tree at that block, which
	// is the signal to try the next candidate nonce (same UX as before).
	const node = await getAztecNode();
	let witness: { leafIndex: bigint; siblingPath: readonly { toString(): string }[] } | null = null;
	let usedNonce: bigint = noteNonce;
	let lastErr: unknown = null;
	for (const candidateNonce of matchingNonces) {
		const uniqueNoteHash = await hashUniqueNoteHash(candidateNonce, siloedNoteHash);
		console.log(`Trying nonce ${candidateNonce.toString().slice(0, 12)}... → uniqueHash ${uniqueNoteHash.toString().slice(0, 20)}... at block=${blockNumber}`);
		try {
			const uniqueNoteHashFr = Fr.fromString('0x' + uniqueNoteHash.toString(16).padStart(64, '0'));
			const w = await (node as any).getNoteHashMembershipWitness(blockNumber, uniqueNoteHashFr);
			if (w) {
				witness = w;
				usedNonce = candidateNonce;
				console.log(`  ✓ found in tree at leafIndex ${(w as any).leafIndex?.toString()}`);
				break;
			}
			console.log(`  ✗ not in tree at block ${blockNumber}, trying next candidate`);
		} catch (e) {
			console.log(`  ✗ node error for candidate nonce:`, (e as Error)?.message ?? e);
			lastErr = e;
		}
	}
	if (!witness) {
		throw lastErr ?? new Error(`No matching note found in note hash tree at block ${blockNumber}`);
	}

	console.log('Retrieved merkle witness with index:', witness.leafIndex.toString());

	// Step 5: Format the merkle data for the circuit.
	const merkleData: AztecMerkleData = {
		leaf_index: BigInt(witness.leafIndex.toString()),
		hash_path: witness.siblingPath.map((h) => BigInt(h.toString())),
		leaf_nonce: usedNonce,
		contract_address: contractAddressBigInt,
	};

	console.log('Aztec merkle data generated successfully');
	return merkleData;
}

/**
 * Get empty Aztec merkle data (used when bridging FROM EVM, not from Aztec)
 */
export function getEmptyAztecMerkleData(): AztecMerkleData {
	return {
		leaf_index: 0n,
		hash_path: new Array(AZTEC_TREE_DEPTH).fill(0n),
		leaf_nonce: 0n,
		contract_address: 0n,
	};
}

/**
 * Get empty EVM merkle data (used when bridging FROM Aztec, not from EVM)
 */
export function getEmptyEvmMerkleData(): EvmMerkleData {
	return {
		leaf_index: 0n,
		hash_path: new Array(EVM_TREE_DEPTH).fill(0n),
	};
}

/**
 * Get empty Giga merkle data (used when withdrawing on same chain as deposit)
 */
export function getEmptyGigaMerkleData(): EvmMerkleData {
	return {
		leaf_index: 0n,
		hash_path: new Array(GIGA_TREE_DEPTH).fill(0n),
	};
}

// =============================================================================
// AZTEC -> L1 MERKLE DATA
// =============================================================================

/**
 * Result of getting merkle data for Aztec -> L1 withdrawal
 */
export interface AztecToL1MerkleDataResult {
	/** The Aztec note hash tree root that was included in the gigaRoot */
	aztecLocalRoot: bigint;
	/** The Aztec block number this root came from */
	aztecLocalRootBlockNumber: number;
	/** L1AztecBridgeAdapter's index in the GigaBridge tree */
	aztecLocalRootIndex: number;
	/** Merkle proof that aztecLocalRoot is in gigaRoot */
	gigaMerkleData: EvmMerkleData;
	/** The L1 block where the gigaRoot was constructed */
	gigaRootBlockNumber: number;
}

/**
 * Get Aztec's local root data from GigaBridge events for a specific gigaRoot
 * 
 * This is similar to getLocalRootData but specifically for the L1AztecBridgeAdapter.
 * It finds the transaction where the specific gigaRoot was constructed,
 * then extracts the Aztec local root from the ReceivedNewLocalRoot events.
 * 
 * @param publicClient - Viem public client for L1
 * @param gigaBridgeAddress - GigaBridge contract address
 * @param aztecBridgeAdapterAddress - L1AztecBridgeAdapter contract address
 * @param gigaRoot - The specific gigaRoot value to find
 */
async function getAztecLocalRootData(
	publicClient: PublicClient,
	gigaBridgeAddress: string,
	aztecBridgeAdapterAddress: string,
	chainId: number,
	gigaRoot: bigint
): Promise<{
	aztecLocalRoot: bigint;
	aztecLocalRootBlockNumber: number;
	aztecLocalRootIndex: number;
	gigaRootBlockNumber: number;
}> {
	// Get local root index for L1AztecBridgeAdapter
	const localRootIndexRaw = await publicClient.readContract({
		address: gigaBridgeAddress as `0x${string}`,
		abi: GigaBridgeAbi,
		functionName: 'getLocalRootProvidersIndex',
		args: [aztecBridgeAdapterAddress as `0x${string}`],
	});
	const aztecLocalRootIndex = Number(localRootIndexRaw);
	console.log('L1AztecBridgeAdapter local root index:', aztecLocalRootIndex);

	// Get GigaRoot event for THIS SPECIFIC gigaRoot value
	const gigaRootEvents = await getGigaRootEvents(publicClient, gigaBridgeAddress, chainId, gigaRoot);

	if (gigaRootEvents.length === 0) {
		console.error(`No ConstructedNewGigaRoot event found for gigaRoot: ${gigaRoot}`);
		throw new Error(
			`GigaRoot ${gigaRoot} not found in L1 events. ` +
			'The bridge state may be inconsistent, or the gigaRoot was constructed on a different chain.'
		);
	}

	// Get the most recent event for this gigaRoot
	const gigaRootEvent = gigaRootEvents[gigaRootEvents.length - 1];
	const gigaRootBlockNumber = Number(gigaRootEvent.blockNumber);
	console.log(`Found ConstructedNewGigaRoot event at L1 block ${gigaRootBlockNumber}, tx: ${gigaRootEvent.transactionHash}`);

	// Get transaction receipt to find local root events in the same tx
	const receipt = await publicClient.getTransactionReceipt({
		hash: gigaRootEvent.transactionHash,
	});

	// Parse ReceivedNewLocalRoot events from the same transaction
	let aztecLocalRoot: bigint | null = null;
	let aztecLocalRootBlockNumber = 0;

	// Calculate event signature: keccak256("ReceivedNewLocalRoot(uint256,uint40,uint256)")
	const eventSignature = keccak256(toHex('ReceivedNewLocalRoot(uint256,uint40,uint256)'));

	for (const log of receipt.logs) {
		try {
			if (log.topics[0] === eventSignature && log.topics.length >= 3 && log.topics[1] && log.topics[2]) {
				const decodedLocalRoot = BigInt(log.topics[1]);
				const decodedIndex = Number(BigInt(log.topics[2]));
				const decodedBlockNumber = log.data ? BigInt(log.data) : 0n;

				console.log(`Found ReceivedNewLocalRoot: index=${decodedIndex}, localRoot=${decodedLocalRoot.toString().slice(0, 20)}..., blockNumber=${decodedBlockNumber}`);

				if (decodedIndex === aztecLocalRootIndex) {
					aztecLocalRoot = decodedLocalRoot;
					aztecLocalRootBlockNumber = Number(decodedBlockNumber);
					console.log(`Matched Aztec local root (index ${aztecLocalRootIndex}): ${aztecLocalRoot.toString().slice(0, 20)}...`);
					break;
				}
			}
		} catch {
			continue;
		}
	}

	// Fallback: query events directly if not found in transaction logs
	if (!aztecLocalRoot) {
		console.log('Aztec local root not found in transaction logs, querying events directly...');
		const localRootEvents = await getLocalRootEvents(
			publicClient,
			gigaBridgeAddress,
			chainId,
			BigInt(gigaRootBlockNumber)
		);

		const matchingEvent = localRootEvents.find((e) => e.index === aztecLocalRootIndex);
		if (matchingEvent) {
			aztecLocalRoot = matchingEvent.localRoot;
			aztecLocalRootBlockNumber = matchingEvent.blockNumber;
			console.log(`Found Aztec local root from events: ${aztecLocalRoot.toString().slice(0, 20)}... at block ${aztecLocalRootBlockNumber}`);
		}
	}

	if (!aztecLocalRoot) {
		throw new Error(
			`Aztec local root (index ${aztecLocalRootIndex}) not found in giga root construction. ` +
			'The Aztec state may not have been bridged to L1 for this gigaRoot, or L1AztecBridgeAdapter is not registered.'
		);
	}

	return {
		aztecLocalRoot,
		aztecLocalRootBlockNumber,
		aztecLocalRootIndex,
		gigaRootBlockNumber,
	};
}

/**
 * Build Giga merkle proof for Aztec -> L1 withdrawal
 * 
 * This function builds a merkle proof that the Aztec local root is included
 * in the GigaBridge tree that produced the given gigaRoot.
 * 
 * Based on backend/scripts/lib/proving.ts getGigaMerkleData()
 * 
 * @param publicClient - Viem public client for L1
 * @param gigaBridgeAddress - GigaBridge contract address
 * @param aztecLocalRoot - The Aztec note hash tree root to prove
 * @param aztecLocalRootIndex - L1AztecBridgeAdapter's index in GigaBridge
 * @param gigaRootBlockNumber - L1 block where gigaRoot was constructed
 * @param expectedGigaRoot - The expected gigaRoot (for validation)
 */
async function buildGigaMerkleProofForAztec(
	publicClient: PublicClient,
	gigaBridgeAddress: string,
	aztecLocalRoot: bigint,
	aztecLocalRootIndex: number,
	chainId: number,
	gigaRootBlockNumber: number,
	expectedGigaRoot: bigint
): Promise<EvmMerkleData> {
	// Two paths:
	//   (a) default — call BridgeKeeper's /giga-state endpoint, which reads
	//       the tree state in a handful of contract reads (cached 5s). Handles
	//       rate-limit pressure centrally.
	//   (b) user opted into their own RPC — scan events client-side against
	//       their endpoint. We don't know their URL to relay for them, and
	//       they explicitly opted in, so they eat the cost.
	const usingCustomRpc = rpcSettings.isUsingCustom(chainId);
	let sortedLeaves: bigint[];
	let amountOfLocalRoots: number;
	if (!usingCustomRpc) {
		const state = await fetchGigaStateFromKeeper(String(chainId));
		amountOfLocalRoots = state.amountOfLocalRoots;
		sortedLeaves = [];
		for (let i = 0; i < amountOfLocalRoots; i++) {
			const leaf = state.leaves.find((l) => l.index === i);
			sortedLeaves[i] = leaf ? BigInt(leaf.localRoot) : 0n;
		}
		console.log('Amount of local roots in GigaBridge:', amountOfLocalRoots, '(via keeper)');
	} else {
		// Opted-in client-side scan path. Kept for parity with the server
		// aggregator so custom-RPC users aren't locked out of withdrawing.
		amountOfLocalRoots = Number(await publicClient.readContract({
			address: gigaBridgeAddress as `0x${string}`,
			abi: GigaBridgeAbi,
			functionName: 'amountOfLocalRoots',
		}));
		console.log('Amount of local roots in GigaBridge:', amountOfLocalRoots, '(via custom RPC scan)');

		const localRootEvents = await getLocalRootEvents(
			publicClient,
			gigaBridgeAddress,
			chainId,
			BigInt(gigaRootBlockNumber),
		);
		if (localRootEvents.length === 0) {
			throw new Error('No local root events found in GigaBridge');
		}

		const eventsPerIndex: Record<number, typeof localRootEvents> = {};
		for (const event of localRootEvents) {
			if (!eventsPerIndex[event.index]) eventsPerIndex[event.index] = [];
			eventsPerIndex[event.index].push(event);
		}
		sortedLeaves = [];
		for (let i = 0; i < amountOfLocalRoots; i++) {
			if (eventsPerIndex[i] && eventsPerIndex[i].length > 0) {
				const latestEvent = eventsPerIndex[i].reduce((latest, ev) =>
					ev.eventBlockNumber > latest.eventBlockNumber ? ev : latest,
				);
				sortedLeaves[i] = latestEvent.localRoot;
			} else {
				sortedLeaves[i] = 0n;
			}
		}
	}

	console.log('Giga tree sorted leaves:', sortedLeaves.map((l, i) => `[${i}]: ${l.toString().slice(0, 15)}...`));

	// Verify Aztec local root is in tree at the expected index
	if (sortedLeaves[aztecLocalRootIndex] !== aztecLocalRoot) {
		console.error('Mismatch:', {
			expected: aztecLocalRoot.toString(),
			actual: sortedLeaves[aztecLocalRootIndex]?.toString() || 'undefined',
			index: aztecLocalRootIndex
		});
		throw new Error(
			`Aztec local root at index ${aztecLocalRootIndex} does not match expected value. ` +
			`Expected: ${aztecLocalRoot.toString().slice(0, 20)}..., ` +
			`Got: ${sortedLeaves[aztecLocalRootIndex]?.toString().slice(0, 20) || 'undefined'}...`
		);
	}

	// Build merkle tree and get proof using fixed-merkle-tree
	const tree = createPoseidonMerkleTree(GIGA_TREE_DEPTH, sortedLeaves);

	// Validate the recreated giga tree root matches the expected gigaRoot
	const computedGigaRoot = BigInt(tree.root);
	console.log('Giga tree - computed root:', computedGigaRoot.toString());
	console.log('Giga tree - expected gigaRoot:', expectedGigaRoot.toString());

	if (computedGigaRoot !== expectedGigaRoot) {
		throw new Error(
			`Could not recreate the gigaRoot with events. ` +
			`Computed: ${computedGigaRoot}, Expected: ${expectedGigaRoot}. ` +
			`This may indicate missing local root events or timing issues.`
		);
	}

	const proof = getMerkleProof(tree, aztecLocalRoot);

	return {
		leaf_index: BigInt(aztecLocalRootIndex),
		hash_path: proof.pathElements,
	};
}

/**
 * Get all merkle data needed for Aztec -> L1 withdrawal
 * 
 * This function retrieves:
 * 1. The Aztec local root (note hash tree root) that was bridged to L1
 * 2. The Aztec block number this root came from (needed for getAztecMerkleData)
 * 3. The Giga merkle proof (proof that Aztec local root is in gigaRoot)
 * 
 * Usage:
 * ```typescript
 * const { aztecLocalRoot, aztecLocalRootBlockNumber, gigaMerkleData } = 
 *   await getMerkleDataForAztecToL1(chainId, gigaRoot);
 * 
 * // Then get Aztec merkle data using the correct block number
 * const aztecMerkleData = await getAztecMerkleData(wallet, commitment, aztecLocalRootBlockNumber);
 * ```
 * 
 * @param destinationChainId - The L1 chain ID (e.g., 31337 for localhost, 1 for mainnet)
 * @param gigaRoot - The gigaRoot from L1 WarpToad contract
 * @returns Aztec local root data and Giga merkle proof
 */
export async function getMerkleDataForAztecToL1(
	destinationChainId: number,
	gigaRoot: bigint
): Promise<AztecToL1MerkleDataResult> {
	console.log('Getting merkle data for Aztec -> L1 withdrawal');
	console.log('Destination chain ID:', destinationChainId);
	console.log('GigaRoot:', gigaRoot.toString().slice(0, 20) + '...');

	// Get contract addresses
	const addresses = getContractAddresses(destinationChainId);
	if (!addresses.GigaBridge) {
		throw new Error(`GigaBridge address not found for chain ${destinationChainId}`);
	}
	if (!addresses.L1AztecBridgeAdapter) {
		throw new Error(`L1AztecBridgeAdapter address not found for chain ${destinationChainId}`);
	}

	console.log('GigaBridge:', addresses.GigaBridge);
	console.log('L1AztecBridgeAdapter:', addresses.L1AztecBridgeAdapter);

	// Create public client for L1
	const publicClient = createEvmClient(destinationChainId);

	// Step 1: Get Aztec's local root + L2 block directly from the L1AztecBridgeAdapter
	// (mostRecentL2Root / mostRecentL2RootBlockNumber). This is the canonical source
	// of truth - parsing ConstructedNewGigaRoot events is brittle when the same
	// gigaRoot value recurs across runs.
	//
	// getLocalRootAndBlock() reverts with a cryptic "refreshRoot must be called"
	// message whenever the Aztec L2→L1 sync hasn't landed yet, so we pre-check
	// mostRecentL2Root and surface an actionable message. The Aztec leg takes
	// 30-90 min on testnet (prover lag + outbox settle) and users hitting this
	// usually just need to wait, not chase a bug.
	const mostRecentL2Root = await publicClient.readContract({
		address: addresses.L1AztecBridgeAdapter as `0x${string}`,
		abi: [{
			type: 'function', name: 'mostRecentL2Root', stateMutability: 'view',
			inputs: [], outputs: [{ type: 'uint256' }],
		}],
		functionName: 'mostRecentL2Root',
	}) as bigint;
	if (mostRecentL2Root === 0n) {
		throw new Error('Aztec root not yet synced to L1. Try again in 30-90 min.');
	}

	const [adapterLocalRoot, adapterLocalRootBlock] = await publicClient.readContract({
		address: addresses.L1AztecBridgeAdapter as `0x${string}`,
		abi: [{
			type: 'function', name: 'getLocalRootAndBlock', stateMutability: 'view',
			inputs: [], outputs: [{ type: 'uint256' }, { type: 'uint256' }],
		}],
		functionName: 'getLocalRootAndBlock',
	}) as [bigint, bigint];
	const aztecLocalRoot = adapterLocalRoot;
	const aztecLocalRootBlockNumber = Number(adapterLocalRootBlock);

	// We still need the index of L1AztecBridgeAdapter in GigaBridge's localRootProviders,
	// and the L1 block where the matching gigaRoot was constructed (for the giga proof).
	const localRootIndexRaw = await publicClient.readContract({
		address: addresses.GigaBridge as `0x${string}`,
		abi: GigaBridgeAbi,
		functionName: 'getLocalRootProvidersIndex',
		args: [addresses.L1AztecBridgeAdapter as `0x${string}`],
	});
	const aztecLocalRootIndex = Number(localRootIndexRaw);

	const gigaRootEvents = await getGigaRootEvents(publicClient, addresses.GigaBridge, destinationChainId, gigaRoot);
	if (gigaRootEvents.length === 0) {
		throw new Error(`GigaRoot ${gigaRoot} not found in L1 events.`);
	}
	const gigaRootBlockNumber = Number(gigaRootEvents[gigaRootEvents.length - 1].blockNumber);

	console.log('Aztec local root:', aztecLocalRoot.toString().slice(0, 20) + '...');
	console.log('Aztec local root block number:', aztecLocalRootBlockNumber);
	console.log('Aztec local root index in GigaBridge:', aztecLocalRootIndex);

	// Step 2: Build Giga merkle proof
	const gigaMerkleData = await buildGigaMerkleProofForAztec(
		publicClient,
		addresses.GigaBridge,
		aztecLocalRoot,
		aztecLocalRootIndex,
		destinationChainId,
		gigaRootBlockNumber,
		gigaRoot
	);

	console.log('Giga merkle proof generated successfully');
	console.log('Leaf index:', gigaMerkleData.leaf_index.toString());
	console.log('Hash path length:', gigaMerkleData.hash_path.length);

	return {
		aztecLocalRoot,
		aztecLocalRootBlockNumber,
		aztecLocalRootIndex,
		gigaMerkleData,
		gigaRootBlockNumber,
	};
}
