
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
    //@ts-ignore
} from '@aztec/aztec.js';
  //@ts-ignore
import WarpToadCoreContractArtifactJson from '../../target/WarpToadCore-WarpToadCore.json' with { type: 'json' };
export const WarpToadCoreContractArtifact = loadContractArtifact(WarpToadCoreContractArtifactJson as NoirCompiledContract);


      export type Transfer = {
        from: AztecAddressLike
to: AztecAddressLike
amount: (bigint | number)
      }
    

      export type NewGigaRoot = {
        giga_root: FieldLike
block_number: (bigint | number)
      }
    

/**
 * Type-safe interface for contract WarpToadCore;
 */
export class WarpToadCoreContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, WarpToadCoreContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, WarpToadCoreContract.artifact, wallet) as Promise<WarpToadCoreContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, native_token: EthAddressLike, _name: string, _symbol: string, _decimals: (bigint | number)) {
    return new DeployMethod<WarpToadCoreContract>(PublicKeys.default(), wallet, WarpToadCoreContractArtifact, WarpToadCoreContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, native_token: EthAddressLike, _name: string, _symbol: string, _decimals: (bigint | number)) {
    return new DeployMethod<WarpToadCoreContract>(publicKeys, wallet, WarpToadCoreContractArtifact, WarpToadCoreContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof WarpToadCoreContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<WarpToadCoreContract['methods'][M]>
  ) {
    return new DeployMethod<WarpToadCoreContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      WarpToadCoreContractArtifact,
      WarpToadCoreContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return WarpToadCoreContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(WarpToadCoreContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'giga_root' | 'native_token' | 'balances' | 'commitments' | 'symbol' | 'name' | 'decimals' | 'deployer' | 'giga_root_provider' | 'l1_bridge_adapter'> {
      return {
        giga_root: {
      slot: new Fr(1n),
    },
native_token: {
      slot: new Fr(2n),
    },
balances: {
      slot: new Fr(4n),
    },
commitments: {
      slot: new Fr(5n),
    },
symbol: {
      slot: new Fr(6n),
    },
name: {
      slot: new Fr(8n),
    },
decimals: {
      slot: new Fr(10n),
    },
deployer: {
      slot: new Fr(12n),
    },
giga_root_provider: {
      slot: new Fr(14n),
    },
l1_bridge_adapter: {
      slot: new Fr(16n),
    }
      } as ContractStorageLayout<'giga_root' | 'native_token' | 'balances' | 'commitments' | 'symbol' | 'name' | 'decimals' | 'deployer' | 'giga_root_provider' | 'l1_bridge_adapter'>;
    }
    

  public static get notes(): ContractNotes<'ValueNote' | 'UintNote' | 'WarpToadNote'> {
    return {
      ValueNote: {
          id: new NoteSelector(0),
        },
UintNote: {
          id: new NoteSelector(1),
        },
WarpToadNote: {
          id: new NoteSelector(2),
        }
    } as ContractNotes<'ValueNote' | 'UintNote' | 'WarpToadNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** balance_of(owner: struct) */
    balance_of: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** burn(amount: integer, destination_chain_id: field, secret: field, nullifier_preimage: field) */
    burn: ((amount: (bigint | number), destination_chain_id: FieldLike, secret: FieldLike, nullifier_preimage: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(native_token: struct, _name: string, _symbol: string, _decimals: integer) */
    constructor: ((native_token: EthAddressLike, _name: string, _symbol: string, _decimals: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_chain_id_unconstrained(aztec_version: field) */
    get_chain_id_unconstrained: ((aztec_version: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_decimals() */
    get_decimals: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_giga_root() */
    get_giga_root: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_l1_bridge_adapter() */
    get_l1_bridge_adapter: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_note_proof(block_number: integer, note_hash: field) */
    get_note_proof: ((block_number: (bigint | number), note_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_version() */
    get_version: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initialize(_giga_root_provider: struct, _l1_bridge_adapter: struct) */
    initialize: ((_giga_root_provider: AztecAddressLike, _l1_bridge_adapter: EthAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_for_testing(amount: integer, recipient: struct) */
    mint_for_testing: ((amount: (bigint | number), recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_giga_root_evm(amount: integer, secret: field, nullifier_preimage: field, recipient: struct, block_number: integer, origin_local_root: field, giga_merkle_data: struct, evm_merkle_data: struct) */
    mint_giga_root_evm: ((amount: (bigint | number), secret: FieldLike, nullifier_preimage: FieldLike, recipient: AztecAddressLike, block_number: (bigint | number), origin_local_root: FieldLike, giga_merkle_data: { leaf_index: FieldLike, hash_path: FieldLike[] }, evm_merkle_data: { leaf_index: FieldLike, hash_path: FieldLike[] }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_get_name() */
    public_get_name: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_get_symbol() */
    public_get_symbol: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** receive_giga_root(giga_root: field) */
    receive_giga_root: ((giga_root: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer(to: struct, amount: integer) */
    transfer: ((to: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { Transfer: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, NewGigaRoot: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      Transfer: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "from",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "to",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 64
            }
        }
    ],
    "path": "WarpToadCore::Transfer"
},
        eventSelector: EventSelector.fromString("0x3870eeb5"),
        fieldNames: ["from","to","amount"],
      },
NewGigaRoot: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "giga_root",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "block_number",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 32
            }
        }
    ],
    "path": "WarpToadCore::NewGigaRoot"
},
        eventSelector: EventSelector.fromString("0xfa872b11"),
        fieldNames: ["giga_root","block_number"],
      }
    };
  }
  
}
